### PR TITLE
Replace close() call in Flush() with writeback of dirty data to backing storage (Fix for #3381)

### LINKED ISSUE #3381: Rclone mount VFS cache doesn't appear to handle dup() calls gracefully
#### What is the problem you are having with rclone?
I'm trying to use bup to backup to a mounted rclone crypt backend.

When it tries to write midx or bloom files, I get the following error:

    Traceback (most recent call last):    
      File "/usr/lib/bup/cmd/bup-midx", line 272, in <module>
        do_midx_dir(path, opt.output)
      File "/usr/lib/bup/cmd/bup-midx", line 213, in do_midx_dir
        all = list(do_midx_group(path, outfilename, part1)) + part2
      File "/usr/lib/bup/cmd/bup-midx", line 230, in do_midx_group
        rv = _do_midx(outdir, outfilename, sublist, gprefix)
      File "/usr/lib/bup/cmd/bup-midx", line 135, in _do_midx
        f.write('\0'.join(allfilenames))
      File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
        self.gen.next()
      File "/usr/lib/bup/bup/helpers.py", line 723, in atomically_replaced_file
        f.close()
    IOError: [Errno 9] Bad file descriptor

I think the source of this error is that bup opens up the midx file for writing, getting file handle 3 (see strace log below). It then mmap's that file, which ends up doing a dup() syscall under the hood, giving us a second file handle 17. When it's finished with the mmap'ed file handle, it calls close() on it. Rclone sees the close() call for 17, but doesn't account for the fact that file handle 3 is still open. It uploads the file and deletes the local copy, invalidating the file handle 3 without bup knowing what has happened.

#### What is your rclone version (output from `rclone version`)
1.48.0

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Arch Linux 64 bit

####  Which cloud storage system are you using? (eg Google Drive)
Box

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

    rclone mount box_crypt: /mnt/box_enc --config /etc/box-webdav/rclone.conf \
    --use-mmap --transfers 256 --checkers 512 --checksum --fast-list --rc \
    --vfs-cache-mode full --cache-dir /var/cache/rclone --vfs-cache-max-size 64G \
    --log-file /var/log/rclone.log --log-level DEBUG

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

    2019/07/27 18:36:20 DEBUG : objects/pack/: Lookup: name="tmpagv5oD"
    2019/07/27 18:36:20 DEBUG : objects/pack/: Create: name="tmpagv5oD"
    2019/07/27 18:36:20 DEBUG : objects/pack/tmpagv5oD: Open: flags=O_RDWR|O_CREATE|O_EXCL|0x20000
    2019/07/27 18:36:20 DEBUG : objects/pack/tmpagv5oD(0xc0039e11a0): Opening cached copy with flags=O_RDWR|O_CREATE|O_EXCL|0x20000
    2019/07/27 18:36:20 DEBUG : objects/pack/tmpagv5oD: >Open: fd=objects/pack/tmpagv5oD (rw), err=<nil>
    2019/07/27 18:36:20 DEBUG : objects/pack/: >Create: node=objects/pack/tmpagv5oD, handle=&{objects/pack/tmpagv5oD (rw)}, err=<nil>
    2019/07/27 18:36:20 DEBUG : objects/pack/tmpagv5oD: Attr:
    2019/07/27 18:36:20 DEBUG : objects/pack/tmpagv5oD: >Attr: a=valid=1s ino=0 size=0 mode=-rw-r--r--, err=<nil>
    2019/07/27 18:36:20 DEBUG : &{objects/pack/tmpagv5oD (rw)}: Write: len=12, offset=0
    2019/07/27 18:36:20 DEBUG : &{objects/pack/tmpagv5oD (rw)}: >Write: written=12, err=<nil>
    2019/07/27 18:36:20 DEBUG : objects/pack/tmpagv5oD: Setattr: a=Setattr [ID=0x607c2 Node=0xa5 Uid=0 Gid=0 Pid=15572] size=39516740 handle=0x5 lockowner
    2019/07/27 18:36:20 DEBUG : objects/pack/tmpagv5oD: >Setattr: err=<nil>
    2019/07/27 18:36:20 DEBUG : objects/pack/tmpagv5oD: Attr:
    2019/07/27 18:36:20 DEBUG : objects/pack/tmpagv5oD: >Attr: a=valid=1s ino=0 size=39516740 mode=-rw-r--r--, err=<nil>
    2019/07/27 18:36:20 DEBUG : objects/pack/tmpagv5oD: Fsync:
    2019/07/27 18:36:20 DEBUG : objects/pack/tmpagv5oD: >Fsync: err=<nil>
    2019/07/27 18:36:20 DEBUG : &{objects/pack/tmpagv5oD (rw)}: Read: len=131072, offset=0
    2019/07/27 18:36:20 DEBUG : &{objects/pack/tmpagv5oD (rw)}: >Read: read=131072, err=<nil>
    ...snip...
    2019/07/27 18:36:21 DEBUG : &{objects/pack/tmpagv5oD (rw)}: Write: len=131072, offset=0
    2019/07/27 18:36:21 DEBUG : &{objects/pack/tmpagv5oD (rw)}: >Write: written=131072, err=<nil>
    ...snip...
    2019/07/27 18:36:21 DEBUG : &{objects/pack/tmpagv5oD (rw)}: Flush:
    2019/07/27 18:36:21 DEBUG : objects/pack/tmpagv5oD(0xc0039e11a0): close:
    2019/07/27 18:36:21 DEBUG : objects/pack/tmpagv5oD: Couldn't find file - need to transfer
    2019/07/27 18:36:23 DEBUG : objects/pack/tmpagv5oD: updateTime: setting atime to 2019-07-27 18:36:22.991529142 -0500 CDT
    2019/07/27 18:36:25 INFO  : objects/pack/tmpagv5oD: Copied (new)
    2019/07/27 18:36:25 DEBUG : objects/pack/tmpagv5oD: transferred to remote
    2019/07/27 18:36:25 DEBUG : objects/pack/tmpagv5oD(0xc0039e11a0): >close: err=<nil>
    2019/07/27 18:36:25 DEBUG : &{objects/pack/tmpagv5oD (rw)}: >Flush: err=<nil>
    2019/07/27 18:36:25 DEBUG : objects/pack/tmpagv5oD: Fsync:
    2019/07/27 18:36:25 DEBUG : objects/pack/tmpagv5oD: >Fsync: err=<nil>
    2019/07/27 18:36:25 DEBUG : objects/pack/tmpagv5oD: Attr:
    2019/07/27 18:36:25 DEBUG : objects/pack/tmpagv5oD: >Attr: a=valid=1s ino=0 size=39516740 mode=-rw-r--r--, err=<nil>
    2019/07/27 18:36:25 DEBUG : &{objects/pack/tmpagv5oD (rw)}: Write: len=549, offset=39516740
    2019/07/27 18:36:25 DEBUG : &{objects/pack/tmpagv5oD (rw)}: >Write: written=0, err=bad file descriptor
    2019/07/27 18:36:25 DEBUG : &{objects/pack/tmpagv5oD (rw)}: Flush:
    2019/07/27 18:36:25 DEBUG : objects/pack/tmpagv5oD(0xc0039e11a0): RWFileHandle.Flush nothing to do
    2019/07/27 18:36:25 DEBUG : &{objects/pack/tmpagv5oD (rw)}: >Flush: err=<nil>
    2019/07/27 18:36:25 DEBUG : &{objects/pack/tmpagv5oD (rw)}: Release:
    2019/07/27 18:36:25 DEBUG : objects/pack/tmpagv5oD(0xc0039e11a0): RWFileHandle.Release nothing to do
    2019/07/27 18:36:25 DEBUG : &{objects/pack/tmpagv5oD (rw)}: >Release: err=<nil>
    2019/07/27 18:36:25 DEBUG : objects/pack/: Lookup: name="tmpagv5oD"
    2019/07/27 18:36:25 DEBUG : objects/pack/: >Lookup: node=objects/pack/tmpagv5oD, err=<nil>
    2019/07/27 18:36:25 DEBUG : objects/pack/tmpagv5oD: Attr:
    2019/07/27 18:36:25 DEBUG : objects/pack/tmpagv5oD: >Attr: a=valid=1s ino=0 size=39516740 mode=-rw-r--r--, err=<nil>
    2019/07/27 18:36:25 DEBUG : objects/pack/: Remove: name="tmpagv5oD"
    2019/07/27 18:36:26 INFO  : objects/pack/tmpagv5oD: Removed from cache

### strace log

    openat(AT_FDCWD, "/mnt/box_enc/objects/pack/tmpagv5oD", O_RDWR|O_CREAT|O_EXCL|O_NOFOLLOW, 0600) = 3
    fcntl(3, F_GETFD)                       = 0
    fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
    fstat(3, {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
    fcntl(3, F_GETFL)                       = 0x28002 (flags O_RDWR|O_LARGEFILE|O_NOFOLLOW)
    fstat(3, {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
    lseek(3, 0, SEEK_CUR)                   = 0
    lseek(3, 0, SEEK_CUR)                   = 0
    write(3, "MIDX\0\0\0\4\0\0\0\r", 12)    = 12
    ftruncate(3, 39516740)                  = 0
    lseek(3, 12, SEEK_SET)                  = 12
    fdatasync(3)                            = 0
    fstat(3, {st_mode=S_IFREG|0644, st_size=39516740, ...}) = 0
    fstat(3, {st_mode=S_IFREG|0644, st_size=39516740, ...}) = 0
    dup(3)                                  = 17
    mmap(NULL, 39516740, PROT_READ|PROT_WRITE, MAP_SHARED, 3, 0) = 0x7fc0dda36000
    write(2, "midx: writing 0.00% (0/1645165)\r", 32) = 32
    ...snip...
    write(2, "midx: writing 99.61% (1638784/16"..., 39) = 39
    close(17)                               = 0
    msync(0x7fc0dda36000, 39516740, MS_SYNC) = 0
    munmap(0x7fc0dda36000, 39516740)        = 0
    fstat(3, {st_mode=S_IFREG|0644, st_size=39516740, ...}) = 0
    lseek(3, 39516740, SEEK_SET)            = 39516740
    write(3, "pack-54b98568f664f25c55f780c7daa"..., 549) = -1 EBADF (Bad file descriptor)
    close(3)                                = 0
    unlink("/mnt/box_enc/objects/pack/tmpagv5oD") = 0

### PR DESCRIPTION
**Pull request by bdutro**
#### What is the purpose of this change?

vfs: move writeback of dirty data out of close() method into its own method (FlushWrites) and remove close() call from Flush()
    
If a file handle is duplicated with dup() and the duplicate handle is flushed, rclone will go ahead and close the file, making the original file handle stale. This change removes the close() call from Flush() and replaces it with FlushWrites() so that the file only gets closed when Release() is called. The new FlushWrites method takes care of actually writing the file back to the underlying storage.

Fixes #3381

#### Was the change discussed in an issue or in the forum before?

https://github.com/rclone/rclone/issues/3381
https://forum.rclone.org/t/rclone-mount-vfs-cache-doesnt-appear-to-handle-dup-calls-gracefully/11030

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [x] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

File: vfs/read_write_test.go [hunk 1]
```diff
@@ -604,3 +610,38 @@ func TestRWFileModTimeWithOpenWriters(t *testing.T) {
...
 }
+
+// tests behavior of mmap() in Python by using dup() on a file handle
+func TestRWFileDup(t *testing.T) {
+	r := fstest.NewRun(t)
+	defer r.Finalise()
+
+	_, fh := rwHandleCreateWriteOnly(t, r)
+
+	test_data := []byte("0123456789")
```
Comment (golangcibot) [inline vfs/read_write_test.go]: don't use underscores in Go names; var `test_data` should be `testData` (from `golint`)

File: vfs/read_write_test.go [hunk 2]
```diff
@@ -604,3 +610,38 @@ func TestRWFileModTimeWithOpenWriters(t *testing.T) {
...
+
+	err := fh.Truncate(int64(len(test_data) + 2))
+	require.NoError(t, err)
+
+	err = fh.Flush()
+	require.NoError(t, err)
+
+	dup_fd, err := syscall.Dup(int(fh.Fd()))
```
Comment (golangcibot) [inline vfs/read_write_test.go]: don't use underscores in Go names; var `dup_fd` should be `dupFd` (from `golint`)

File: vfs/read_write_test.go [hunk 3]
```diff
@@ -604,3 +610,38 @@ func TestRWFileModTimeWithOpenWriters(t *testing.T) {
...
+	require.NoError(t, err)
+
+	dup_file := os.NewFile(uintptr(dup_fd), fh.file.Name())
```
Comment (golangcibot) [inline vfs/read_write_test.go]: don't use underscores in Go names; var `dup_file` should be `dupFile` (from `golint`)

File: vfs/read_write_test.go (hunk 1 above)
Comment (bdutro) [reply vfs/read_write_test.go]: Fixed

File: vfs/read_write_test.go (hunk 2 above)
Comment (bdutro) [reply vfs/read_write_test.go]: Fixed

File: vfs/read_write_test.go (hunk 3 above)
Comment (bdutro) [reply vfs/read_write_test.go]: Fixed

File: vfs/read_write_test_unix.go [hunk 4]
```diff
@@ -0,0 +1,51 @@
...
+	"github.com/rclone/rclone/fstest"
+	"github.com/stretchr/testify/require"
+)
+
+func dup(oldfd uintptr) (uintptr, error) {
+	newfd, err := unix.Dup(int(oldfd))
+	return uintptr(newfd), err
+}
+
+// tests behavior of mmap() in Python by using dup() on a file handle
```
Comment (golangcibot) [inline vfs/read_write_test_unix.go]: comment on exported function `TestRWFileDup` should be of the form `TestRWFileDup ...` (from `golint`)

File: vfs/vfs_test_syscalls_unix.go [hunk 5]
```diff
@@ -0,0 +1,10 @@
+package vfs
+
+import (
+	"golang.org/x/sys/unix"
+)
+
+func Dup(oldfd uintptr) (uintptr, error) {
```
Comment (golangcibot) [inline vfs/vfs_test_syscalls_unix.go]: exported function `Dup` should have comment or be unexported (from `golint`)

**Comment by bdutro** [comment]
Sorry for all the pushes - this is my first time working with Go

File: vfs/read_write.go [hunk 6]
```diff
@@ -230,28 +230,14 @@ func (fh *RWFileHandle) modified() bool {
...
-// to give the user a chance to recover it.
-func (fh *RWFileHandle) close() (err error) {
-	defer log.Trace(fh.logPrefix(), "")("err=%v", &err)
-	fh.file.muRW.Lock()
-	defer fh.file.muRW.Unlock()
-
-	if fh.closed {
-		return ECLOSED
+// Must be called with fh.muRW held
+func (fh *RWFileHandle) FlushWrites(closeFile bool) error {
```
Comment (ncw) [inline vfs/read_write.go]: This should be `flushWrites` so it isn't a public symbol - it can't be safely called outside the package anyway with the locking requirement.

**Comment by bdutro** [comment]
The Python script passes with my changes, but I just realized that the unit test I added is passing even if I remove my changes. I think I might not be accessing the right file handle to replicate the behavior of the script.

**Comment by bdutro** [comment]
I ran with strace and it looks like I'm operating directly on the file in the VFS cache instead of through a FUSE mount. There's probably a level of indirection that I'm bypassing because of that.

**Comment by bdutro** [comment]
I moved the unit test into the mount tests and was able to see a difference with and without my changes. I also found what looks like a bug in vfs.SetCacheMode - the mode was never actually getting changed if the previous cache mode was CacheModeOff.

File: cmd/mountlib/mounttest/write.go [hunk 7]
```diff
@@ -82,3 +85,47 @@ func TestWriteFileFsync(t *testing.T) {
...
+func TestWriteFileDup(t *testing.T) {
+	run.skipIfNoFUSE(t)
+
+	if run.vfs.Opt.CacheMode < vfs.CacheModeWrites {
+	    t.Skip("not supported on vfs-cache-mode < writes")
+		return
+    }
+
+	filepath := run.path("to be synced")
+	fh, err := osCreate(filepath)
```
Comment (golangcibot) [inline cmd/mountlib/mounttest/write.go]: ineffectual assignment to `err` (from `ineffassign`)

File: cmd/mountlib/mounttest/write.go [hunk 8]
```diff
@@ -2,9 +2,12 @@ package mounttest
 
 import (
 	"testing"
+	"os"
```
Comment (golangcibot) [inline cmd/mountlib/mounttest/write.go]: File is not `goimports`-ed (from `goimports`)
```suggestion
	"os"
	"testing"
```

File: cmd/mountlib/mounttest/write_unix.go [hunk 9]
```diff
@@ -4,9 +4,9 @@ package mounttest
 
 import (
 	"runtime"
-	"syscall"
 	"testing"
 
+	"golang.org/x/sys/unix"
```
Comment (golangcibot) [inline cmd/mountlib/mounttest/write_unix.go]: File is not `goimports`-ed (from `goimports`)
```suggestion

```

File: cmd/mountlib/mounttest/write.go [hunk 10]
```diff
@@ -82,3 +85,48 @@ func TestWriteFileFsync(t *testing.T) {
 	run.waitForWriters()
 	run.rm(t, "to be synced")
 }
+
+// TestWriteFileDup tests behavior of mmap() in Python by using dup() on a file handle
+func TestWriteFileDup(t *testing.T) {
+	run.skipIfNoFUSE(t)
+
+	if run.vfs.Opt.CacheMode < vfs.CacheModeWrites {
+	    t.Skip("not supported on vfs-cache-mode < writes")
```
Comment (golangcibot) [inline cmd/mountlib/mounttest/write.go]: File is not `goimports`-ed (from `goimports`)
```suggestion
		t.Skip("not supported on vfs-cache-mode < writes")
```

File: cmd/mountlib/mounttest/write.go [hunk 11]
```diff
@@ -82,3 +85,48 @@ func TestWriteFileFsync(t *testing.T) {
...
 }
+
+// TestWriteFileDup tests behavior of mmap() in Python by using dup() on a file handle
+func TestWriteFileDup(t *testing.T) {
+	run.skipIfNoFUSE(t)
+
+	if run.vfs.Opt.CacheMode < vfs.CacheModeWrites {
+		t.Skip("not supported on vfs-cache-mode < writes")
+		return
+    }
```
Comment (golangcibot) [inline cmd/mountlib/mounttest/write.go]: File is not `goimports`-ed (from `goimports`)
```suggestion
	}
```

**Comment by ncw** [comment]
> I moved the unit test into the mount tests and was able to see a difference with and without my changes.

That is perfect - thanks.

> I also found what looks like a bug in vfs.SetCacheMode - the mode was never actually getting changed if the previous cache mode was CacheModeOff.

Hmm, very strange and well spotted!

Thanks for fixing this - I'll merge now.

Do you like working on this sort of stuff, filesystems VFS layers etc? I'm impressed with you diving into what is a very complicated part of the program in a language you've only just learnt!

There are more VFS things which need fixing up if you've got time?

**Comment by bdutro** [comment]
I do have a fair bit of free time at the moment. I'd be happy to look at some bugs if you want.

**Comment by ncw** [comment]
Here are some VFS issues which you may be interested in!

- https://github.com/rclone/rclone/issues/3562
- https://github.com/rclone/rclone/issues/3270

Also I have this outstanding PR which needs finishing off

- https://github.com/rclone/rclone/pull/3480
