### PR TITLE
dlna: correct output for ContentDirectoryService#Browse with BrowseMe…

### LINKED ISSUE #3253: Serve DLNA not working on Samsung TV
#### What is the problem you are having with rclone?
TV shows no playable content from DLNA share. I can see it under sources, but after choosing it, it tells me "the content cannot be displayed"

#### What is your rclone version (output from `rclone version`)
rclone v1.47.0-115-g2c72e7f0-beta

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Debian 9, 64 Bit

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone serve dlna remote:Media

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
rclone -vvv serve dlna gcrypt:Media/Movies                     
2019/06/11 10:39:59 DEBUG : rclone: Version "v1.47.0-115-g2c72e7f0-beta" starting with parameters ["rclone" "-vvv" "serve" "dlna" "remote:Media/"]
Enter configuration password:                               
password:
2019/06/11 10:40:04 DEBUG : Using config file from "/home/user/.config/rclone/rclone.conf"
2019/06/11 10:40:07 DEBUG : Adding path "vfs/forget" to remote control registry
2019/06/11 10:40:07 DEBUG : Adding path "vfs/refresh" to remote control registry  
2019/06/11 10:40:07 DEBUG : Adding path "vfs/poll-interval" to remote control registry
2019/06/11 10:40:07 NOTICE: Encrypted drive 'remote:Media/': Serving HTTP on [::]:7879
2019/06/11 10:40:07 INFO  : DLNA server on :7879: Started SSDP on lo
2019/06/11 10:40:07 INFO  : DLNA server on :7879: Started SSDP on vethecf93a0               
2019/06/11 10:40:07 INFO  : DLNA server on :7879: Started SSDP on br-ff002a7d26fd                
2019/06/11 10:40:07 INFO  : DLNA server on :7879: Started SSDP on docker0                        
2019/06/11 10:40:07 INFO  : DLNA server on :7879: Started SSDP on br-7929a085d1c8                 
2019/06/11 10:40:07 INFO  : DLNA server on :7879: Started SSDP on enp3s0                                    
2019/06/11 10:40:13 INFO  : /ctl: 192.168.178.57:53172 POST 200 "urn:schemas-upnp-org:service:ContentDirectory:1#Browse" %!s(<nil>)
2019/06/11 10:40:17 INFO  : /ctl: 192.168.178.57:53173 POST 200 "urn:schemas-upnp-org:service:ContentDirectory:1#Browse" %!s(<nil>)
2019/06/11 10:40:17 INFO  : /ctl: 192.168.178.57:53174 POST 200 "urn:schemas-upnp-org:service:ContentDirectory:1#Browse" %!s(<nil>)
2019/06/11 10:40:21 INFO  : /ctl: 192.168.178.57:53175 POST 200 "urn:schemas-upnp-org:service:ContentDirectory:1#Browse" %!s(<nil>)
2019/06/11 10:40:21 INFO  : /ctl: 192.168.178.57:53176 POST 200 "urn:schemas-upnp-org:service:ContentDirectory:1#Browse" %!s(<nil>)

Every time i clicked on refresh (in the tv), i got 2 of these POST 200 messages.

To check, that the share is working properly i also tested it with VLC on my Android device and got it working. So the combination of rclone-dlna and my Samsung is not working at the moment.

### PR DESCRIPTION
**Pull request by sretlawd**
…tadata

We were marshalling the "cds object" instead of the "upnp object".

Fixes #3253  (I think)

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [x] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

File: cmd/serve/dlna/cds.go [hunk 1]
```diff
@@ -245,7 +245,12 @@ func (cds *contentDirectoryService) Handle(action string, argsXML []byte, r *htt
 				"UpdateID":       cds.updateIDString(),
 			}, nil
 		case "BrowseMetadata":
-			result, err := xml.Marshal(obj)
+			node, err := cds.vfs.Stat(obj.Path)
+			if err != nil {
+				return nil, err
+			}
+			upnpObject, err := cds.cdsObjectToUpnpavObject(obj, node, host)
```
Comment (golangcibot) [inline cmd/serve/dlna/cds.go]: ineffectual assignment to `err` (from `ineffassign`)

Comment (sretlawd) [reply cmd/serve/dlna/cds.go]: fixed

**Comment by ncw** [comment]
That looks great - thank you.

Will merge now :-)
