### PR TITLE
docs: Improve `rclone ls` docs - fixes rclone#9028

### LINKED ISSUE #9028: Docs for `rclone ls/lsl/lsd/lsf` are misleading
#### The associated forum post URL from `https://forum.rclone.org`

none

#### What is the problem you are having with rclone?

I thought `rclone ls/lsl/lsd -R/lsf -R` uses `List` recursively if `--fast-list` option is not passed because [the documentation](https://rclone.org/commands/rclone_ls/#listing-options) mentions about the option. But actually `rclone ls/lsl/lsd -R/lsf -R` uses `ListR` regardless of the `--fast-list` option.

I tried to update the doc, but the doc is autogenerated and the problematic part is shared by other commands that `--fast-list` actually has an effect. I'm not sure how to change the gendoc sources. So I'm filing an issue for now.

#### What is your rclone version (output from `rclone version`)

```
rclone v1.72.0
- os/version: Microsoft Windows 11 Pro 25H2 25H2 (64 bit)
- os/kernel: 10.0.26200.7462 (x86_64)
- os/type: windows
- os/arch: amd64
- go/version: go1.25.4
- go/linking: static
- go/tags: cmount
```

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Windows 11, 64 bit

#### Which cloud storage system are you using? (e.g. Google Drive)

pCloud

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

```
rclone -vv lsf -R pcloud:crypt/d3f03alho8k7767so5g0279064
```
```
rclone -vv lsf -R --disable ListR pcloud:crypt/d3f03alho8k7767so5g0279064
```
```
rclone -vv lsf -R --fast-list pcloud:crypt/d3f03alho8k7767so5g0279064
```

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

```
2025/12/12 05:41:37 DEBUG : rclone: Version "v1.72.0" starting with parameters ["rclone" "-vv" "lsf" "-R" "pcloud:crypt/d3f03alho8k7767so5g0279064"]
2025/12/12 05:41:37 DEBUG : Creating backend with remote "pcloud:crypt/d3f03alho8k7767so5g0279064"
2025/12/12 05:41:37 DEBUG : Using config file from "C:\\Users\\****\\AppData\\Roaming\\rclone\\rclone.conf"
s1ettc2k9dckhrecu70hi1h49o/
s1ettc2k9dckhrecu70hi1h49o/cp6el8cugr71n1n4nsof2t3cpk
airs7rla92m8q5f4fun98e3b9c
n748se6k1i03qki27eke376nr4
r165ff1lac411dq7r3kpj90mnk
2025/12/12 05:41:38 DEBUG : 3 go routines active
```
```
2025/12/12 05:42:11 DEBUG : rclone: Version "v1.72.0" starting with parameters ["rclone" "-vv" "lsf" "-R" "--disable" "ListR" "pcloud:crypt/d3f03alho8k7767so5g0279064"]
2025/12/12 05:42:11 DEBUG : Creating backend with remote "pcloud:crypt/d3f03alho8k7767so5g0279064"
2025/12/12 05:42:11 DEBUG : Using config file from "C:\\Users\\****\\AppData\\Roaming\\rclone\\rclone.conf"
2025/12/12 05:42:11 DEBUG : Reset feature "ListR"
airs7rla92m8q5f4fun98e3b9c
n748se6k1i03qki27eke376nr4
r165ff1lac411dq7r3kpj90mnk
s1ettc2k9dckhrecu70hi1h49o/
s1ettc2k9dckhrecu70hi1h49o/cp6el8cugr71n1n4nsof2t3cpk
2025/12/12 05:42:12 DEBUG : 3 go routines active
```
```
2025/12/12 06:02:36 DEBUG : rclone: Version "v1.72.0" starting with parameters ["rclone" "-vv" "lsf" "-R" "--fast-list" "pcloud:crypt/d3f03alho8k7767so5g0279064"]
2025/12/12 06:02:36 DEBUG : Creating backend with remote "pcloud:crypt/d3f03alho8k7767so5g0279064"
2025/12/12 06:02:36 DEBUG : Using config file from "C:\\Users\\****\\AppData\\Roaming\\rclone\\rclone.conf"
s1ettc2k9dckhrecu70hi1h49o/
s1ettc2k9dckhrecu70hi1h49o/cp6el8cugr71n1n4nsof2t3cpk
airs7rla92m8q5f4fun98e3b9c
n748se6k1i03qki27eke376nr4
r165ff1lac411dq7r3kpj90mnk
2025/12/12 06:02:38 DEBUG : 3 go routines active
```
(My user name is redacted.)

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

### PR DESCRIPTION
**Pull request by vyv03354**
#### What is the purpose of this change?

Fixes #9028.

#### Was the change discussed in an issue or in the forum before?

#9028

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [ ] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by vyv03354** [comment]
Why the test failed? I do not touch `cmd/bisync` at all. Is this an existing intermittent failure?

File: cmd/ls/lshelp/lshelp.go [hunk 1]
```diff
@@ -26,6 +26,8 @@ Note that |ls| and |lsl| recurse by default - use |--max-depth 1| to stop the re
 The other list commands |lsd|,|lsf|,|lsjson| do not recurse by default -
 use |-R| to make them recurse.
 
+List commands prefer a recursive method that uses more memory but fewer transactions by default. Use |--disable ListR| to suppress the behavior. See [|--fast-list|](https://rclone.org/docs/#fast-list) for more details.
```
Comment (albertony) [inline cmd/ls/lshelp/lshelp.go]: We normally use urls relative to the domain, i.e. `/docs/#fast-list` in this case. Then it will work also in our test site, https://tip.rclone.org.

**Comment by albertony** [comment]
Thank you. 

One minor comment, other than that I think it is good.

> Why the test failed? I do not touch `cmd/bisync` at all. Is this an existing intermittent failure?

Yes, this is completely unrelated to your changes.

File: cmd/ls/lshelp/lshelp.go (hunk 1 above)
Comment (vyv03354) [reply cmd/ls/lshelp/lshelp.go]: Fixed.

File: cmd/ls/lshelp/lshelp.go [hunk 2]
```diff
@@ -26,6 +26,8 @@ Note that |ls| and |lsl| recurse by default - use |--max-depth 1| to stop the re
 The other list commands |lsd|,|lsf|,|lsjson| do not recurse by default -
 use |-R| to make them recurse.
 
+List commands prefer a recursive method that uses more memory but fewer transactions by default. Use |--disable ListR| to suppress the behavior. See [|--fast-list|](/docs/#fast-list) for more details.
+
```
Comment (albertony) [inline cmd/ls/lshelp/lshelp.go:32]: Oh, sorry for not mentioning this right away; we try to keep lines under 80 characters length, for reasons explained in https://cirosantilli.com/markdown-style-guide/#line-wrapping, and also since much of our markdown text may be used as command help displayed in (different types of) consoles, etc. This is enforced on some of the markdown docs by our linter, checking https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md#md013---line-length, but it does not yet consider markdown generated from .go source such as here.
