### PR TITLE
rc: set url to the first value of rc-addr -- fixes #6641

### LINKED ISSUE #6641: Failing to run rc commands against a specific rc address
#### The associated forum post URL from `https://forum.rclone.org`

N/A

#### What is the problem you are having with rclone?

`rc` commands are failing when run against a specific rc address.

#### What is your rclone version (output from `rclone version`)

```
rclone v1.61.0
- os/version: ubuntu 18.04 (64 bit)
- os/kernel: 5.18.11-xanmod1 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.19.4
- go/linking: static
- go/tags: none
```

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Ubuntu 18.04 (64-bit)

#### Which cloud storage system are you using? (e.g. Google Drive)

N/A

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

`rclone --rc-addr 127.0.0.1:5572 rc core/gc`

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

```
darthshadow@server:~/temp/rclone-v1.61.0-linux-amd64$ ./rclone --rc-addr 127.0.0.1:5572 rc core/gc
2022/12/20 19:31:11 Failed to rc: connection failed: Post "http://[127.0.0.1:5572]/core/gc": dial tcp: lookup 127.0.0.1:5572: no such host
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

### PR DESCRIPTION
**Pull request by darthShadow**
rc: set url to the first value of rc-addr since it has been converted to an array of strings now 

Signed-off-by: Anagh Kumar Baranwal <6824881+darthShadow@users.noreply.github.com>

#### What is the purpose of this change?

rc: set url to the first value of rc-addr since it has been converted to an array of strings now

#### Was the change discussed in an issue or in the forum before?

#6641 

#### Checklist

- [X] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [X] I have added tests for all changes in this PR if appropriate.
- [X] I have added documentation for the changes if appropriate.
- [X] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [X] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

File: cmd/rc/rc.go [hunk 1]
```diff
@@ -155,7 +155,11 @@ func ParseOptions(options []string) (opt map[string]string) {
 // If the user set flagName set the output to its value
 func setAlternateFlag(flagName string, output *string) {
 	if rcFlag := pflag.Lookup(flagName); rcFlag != nil && rcFlag.Changed {
-		*output = rcFlag.Value.String()
+		if sliceValue, ok := rcFlag.Value.(pflag.SliceValue); ok {
+			*output = sliceValue.GetSlice()[0]
```
Comment (ncw) [inline cmd/rc/rc.go:159]: Is there any way that `sliceValue.GetSlice()` can return 0 elements? If so then this needs a bit of `if len(...) > 0 {`

Comment (darthShadow) [reply cmd/rc/rc.go:159]: I wouldn't think this since we are already checking whether the flag has been changed above. I will add a check anyway.

Comment (darthShadow) [reply cmd/rc/rc.go]: Should be fixed.
