### PR TITLE
jottacloud: add support whitelabel versions

### LINKED ISSUE #3818: jottacloud: Get Sky authentication not working
#### What is the problem you are having with rclone?
Setting up a new Get Sky (white label rebranded Jottacloud) remote isn't working now, and gives HTTP error 401 after attempting to provide the personal login token with the new auth system introduced in #3711.

Setting up new Get Sky remotes with the jottacloud backend used to work before the old authentication method was deprecated.

I've confirmed that the login token authentication method is working with Get Sky accounts when using the official jotta-cli client.

#### What is your rclone version (output from `rclone version`)
rclone v1.50.2-090-g0ecb8bc2-beta

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
linux/amd64

####  Which cloud storage system are you using? (eg Google Drive)
Jottacloud/Get Sky

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
`rclone config`

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
```
$ ./rclone -vv config
2019/12/20 15:24:25 DEBUG : rclone: Version "v1.50.2-090-g0ecb8bc2-beta" starting with parameters ["./rclone" "-vv" "config"]
2019/12/20 15:24:25 DEBUG : Using config file from "/home/user/.config/rclone/rclone.conf"
Current remotes:

Name                 Type
====                 ====
gdrive               drive

e) Edit existing remote
n) New remote
d) Delete remote
r) Rename remote
c) Copy remote
s) Set configuration password
q) Quit config
e/n/d/r/c/s/q> n
name> jotta
Type of storage to configure.
Enter a string value. Press Enter for the default ("").
Choose a number from below, or type in your own value
 1 / 1Fichier
   \ "fichier"
 2 / Alias for an existing remote
   \ "alias"
 3 / Amazon Drive
   \ "amazon cloud drive"
 4 / Amazon S3 Compliant Storage Provider (AWS, Alibaba, Ceph, Digital Ocean, Dreamhost, IBM COS, Minio, etc)
   \ "s3"
 5 / Backblaze B2
   \ "b2"
 6 / Box
   \ "box"
 7 / Cache a remote
   \ "cache"
 8 / Citrix Sharefile
   \ "sharefile"
 9 / Dropbox
   \ "dropbox"
10 / Encrypt/Decrypt a remote
   \ "crypt"
11 / FTP Connection
   \ "ftp"
12 / Google Cloud Storage (this is not Google Drive)
   \ "google cloud storage"
13 / Google Drive
   \ "drive"
14 / Google Photos
   \ "google photos"
15 / Hubic
   \ "hubic"
16 / JottaCloud
   \ "jottacloud"
17 / Koofr
   \ "koofr"
18 / Local Disk
   \ "local"
19 / Mail.ru Cloud
   \ "mailru"
20 / Mega
   \ "mega"
21 / Microsoft Azure Blob Storage
   \ "azureblob"
22 / Microsoft OneDrive
   \ "onedrive"
23 / OpenDrive
   \ "opendrive"
24 / Openstack Swift (Rackspace Cloud Files, Memset Memstore, OVH)
   \ "swift"
25 / Pcloud
   \ "pcloud"
26 / Put.io
   \ "putio"
27 / QingCloud Object Storage
   \ "qingstor"
28 / SSH/SFTP Connection
   \ "sftp"
29 / Transparently chunk/split large files
   \ "chunker"
30 / Union merges the contents of several remotes
   \ "union"
31 / Webdav
   \ "webdav"
32 / Yandex Disk
   \ "yandex"
33 / http Connection
   \ "http"
34 / premiumize.me
   \ "premiumizeme"
Storage> jottacloud
** See help for jottacloud backend at: https://rclone.org/jottacloud/ **

Edit advanced config? (y/n)
y) Yes
n) No (default)
y/n>
Remote config
Config outdated - refreshing
Generate a personal login token here: https://www.jottacloud.com/web/secure
Login Token> [token from https://www.getsky.no/web/secure]
2019/12/20 15:24:47 Failed to get oauth token: HTTP error 401 (401 Unauthorized) returned body: "{\"error\":\"invalid_grant\",\"error_description\":\"Invalid user credentials\"}"
```

### PR DESCRIPTION
**Pull request by buengese**
Initial implementation for parsing OAuth endpoints from well-known-link. More changes may be required. Need testing from @nattycleopatra. Attempts to fix #3818

### CODE REVIEW

File: backend/jottacloud/jottacloud.go [hunk 1]
```diff
@@ -49,10 +49,12 @@ const (
 	rootURL           = "https://www.jottacloud.com/jfs/"
 	apiURL            = "https://api.jottacloud.com/"
 	baseURL           = "https://www.jottacloud.com/"
-	tokenURL          = "https://id.jottacloud.com/auth/realms/jottacloud/protocol/openid-connect/token"
+	defaultTokenURL   = "https://id.jottacloud.com/auth/realms/jottacloud/protocol/openid-connect/token"
 	cachePrefix       = "rclone-jcmd5-"
 	configDevice      = "device"
 	configMountpoint  = "mountpoint"
+	configTokenURL    = "tokenURL"
+	configAuthURL     = "authURL"
```
Comment (golangcibot) [inline backend/jottacloud/jottacloud.go]: `configAuthURL` is unused (from `deadcode`)

**Comment by buengese** [comment]
Beta available [here](https://beta.rclone.org/branch/v1.50.2-093-g9d5e4924-jotta_whitelabel-beta/)

**Comment by nattycleopatra** [comment]
I am able to set up new jottacloud remotes with Get Sky login tokens using the beta builds linked above, so this seems to be working great as-is. Thank you so much for looking into and fixing this!

**Comment by buengese** [comment]
So uploads and downloads are working? I was afraid they might be using different endpoints for that too.

**Comment by nattycleopatra** [comment]
I've tested uploads and downloads, and it all just seems to be working fine! Anything else I should be testing?

**Comment by buengese** [comment]
Nah  If it doesn't break during within the next hour or so it's good and we'll merge it.

**Comment by nattycleopatra** [comment]
It looks like the token refresh is currently not working:

```
2019/12/28 21:31:14 Failed to create file system for "getsky:": couldn't get customer info: Get https://api.jottacloud.com/account/v1/customer: oauth2: cannot fetch token: 400 Bad Request
Response: {"error":"invalid_grant","error_description":"Invalid refresh token"}
```

(Whereas a new remote can be set up for the same account with a new login token.)

**Comment by buengese** [comment]
[New beta](https://beta.rclone.org/branch/v1.50.2-093-gc65bfa15-jotta_whitelabel-beta/). Should hopefully work now.

**Comment by nattycleopatra** [comment]
Token refreshing does indeed seem to work now!

**Comment by buengese** [comment]
@ncw Can i get an ok for merge?

**Comment by ncw** [comment]
Sorry for the delay - been hibernating over the Christmas period ;-)

Yes this looks good to me - please merge :-)
