### PR TITLE
selfupdate: fix --quiet option, not quite quiet

### LINKED ISSUE #5505: self update's --quiet option, not quite quiet
#### The associated forum post URL from `https://forum.rclone.org`
https://forum.rclone.org/t/selfupdate-doesnt-seem-to-respect-the-quiet-option/25517/2

#### What is the problem you are having with rclone?
`rclone selfupdate --quiet` yelds the following output when it doesn't need to update itself:
`rclone is up to date`
(the same as _without_ the `--quiet` option)

#### What is your rclone version (output from `rclone version`)
```rclone v1.56.0
- os/version: ubuntu 18.04 (64 bit)
- os/kernel: 5.3.0-7648-generic (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.16.5
- go/linking: static
- go/tags: none
```

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
`$` **`cat /etc/os-release`**
```
NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

#### Which cloud storage system are you using? (e.g. Google Drive)
N/A

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
`sudo rclone selfupdate --quiet`

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
`2021/08/02 09:22:33 Can't set -v and -q`
:-)

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

### PR DESCRIPTION
**Pull request by yedamao**
#### What is the purpose of this change?
migrate `fmt.Print` to log methods in fs pkg.

#### Was the change discussed in an issue or in the forum before?

Fixes #5505

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [ ] I have added tests for all changes in this PR if appropriate.
- [ ] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

File: cmd/selfupdate/selfupdate.go [hunk 1]
```diff
@@ -169,7 +169,7 @@ func InstallUpdate(ctx context.Context, opt *Options) error {
 		} else {
 			err := installPackage(ctx, opt.Beta, newVersion, siteURL, opt.Package)
 			if err == nil {
-				fmt.Printf("Successfully updated rclone package from version %s to version %s\n", oldVersion, newVersion)
+				fs.Infof(nil, "Successfully updated rclone package from version %s to version %s\n", oldVersion, newVersion)
```
Comment (ivandeex) [inline cmd/selfupdate/selfupdate.go:172]: fs.Infof does not need trailing "\n", please remove it

**Review by ivandeex — COMMENTED** [review]
trailing "\n" left...

**Review by ivandeex — COMMENTED** [review]
trailing "\n" left...

File: cmd/selfupdate/selfupdate.go (hunk 1 above)
Comment (yedamao) [reply cmd/selfupdate/selfupdate.go]: ok, fixed

File: cmd/selfupdate/selfupdate.go [hunk 2]
```diff
@@ -169,7 +169,7 @@ func InstallUpdate(ctx context.Context, opt *Options) error {
 		} else {
 			err := installPackage(ctx, opt.Beta, newVersion, siteURL, opt.Package)
 			if err == nil {
-				fmt.Printf("Successfully updated rclone package from version %s to version %s\n", oldVersion, newVersion)
+				fs.Infof(nil, "Successfully updated rclone package from version %s to version %s", oldVersion, newVersion)
```
Comment (ivandeex) [inline cmd/selfupdate/selfupdate.go:172]: Info is only shown when `-v` flag is present.
I think this message should be printed with `fs.Logf` (aka `NOTICE`) so it's visible by default. I'm just not sure that `--quiet` will hide it.

File: cmd/selfupdate/selfupdate.go [hunk 3]
```diff
@@ -221,7 +221,7 @@ func InstallUpdate(ctx context.Context, opt *Options) error {
 
 	err = replaceExecutable(targetFile, newFile, savedFile)
 	if err == nil {
-		fmt.Printf("Successfully updated rclone from version %s to version %s\n", oldVersion, newVersion)
+		fs.Infof(nil, "Successfully updated rclone from version %s to version %s", oldVersion, newVersion)
```
Comment (ivandeex) [inline cmd/selfupdate/selfupdate.go:224]: Same comment as above:
Info is only shown when -v flag is present.
I think this message should be printed with fs.Logf (aka NOTICE) so it's visible by default. I'm just not sure that --quiet will hide it.

File: cmd/selfupdate/selfupdate.go [hunk 4]
```diff
@@ -297,7 +297,7 @@ func replaceExecutable(targetFile, newFile, savedFile string) error {
 			}
 		}
 		if saveErr == nil {
-			fmt.Printf("The old executable was saved as %s\n", savedFile)
+			fs.Infof(nil, "The old executable was saved as %s", savedFile)
```
Comment (ivandeex) [inline cmd/selfupdate/selfupdate.go:300]: `Info` is okay here. User will need `-v` to see this.

File: cmd/selfupdate/selfupdate.go [hunk 5]
```diff
@@ -158,7 +158,7 @@ func InstallUpdate(ctx context.Context, opt *Options) error {
 
 	oldVersion := fs.Version
 	if newVersion == oldVersion {
-		fmt.Println("rclone is up to date")
+		fs.Infof(nil, "rclone is up to date")
```
Comment (ivandeex) [inline cmd/selfupdate/selfupdate.go:161]: This will not be printed by default, only with `-v`. Fine.

**Review by ivandeex — COMMENTED** [review]
Some `fs.Info` should be `fs.Log` IMO.

File: cmd/selfupdate/selfupdate.go (hunk 2 above)
Comment (ivandeex) [reply cmd/selfupdate/selfupdate.go:172]: @yedamao
Could please check that `--quiet` will hide the `fs.Logf` messages?

Comment (yedamao) [reply cmd/selfupdate/selfupdate.go:172]: --quiet/-q will set LogLevvel as LogLevelError, so fs.Logf is ok.

**Comment by yedamao** [comment]
@ivandeex ptal

File: cmd/selfupdate/selfupdate.go (hunk 2 above)
Comment (ivandeex) [reply cmd/selfupdate/selfupdate.go]: Please use Logf here.

File: cmd/selfupdate/selfupdate.go (hunk 3 above)
Comment (ivandeex) [reply cmd/selfupdate/selfupdate.go]: Please use Logf here, too.

File: cmd/selfupdate/selfupdate.go (hunk 2 above)
Comment (yedamao) [reply cmd/selfupdate/selfupdate.go]: this diff is outdated, please check the latest diff.

File: cmd/selfupdate/selfupdate.go (hunk 3 above)
Comment (yedamao) [reply cmd/selfupdate/selfupdate.go]: this diff is outdated, please check the latest diff.🤣

File: cmd/selfupdate/selfupdate.go (hunk 2 above)
Comment (ivandeex) [reply cmd/selfupdate/selfupdate.go]: ah I see now

File: cmd/selfupdate/selfupdate.go (hunk 3 above)
Comment (ivandeex) [reply cmd/selfupdate/selfupdate.go]: 🧑‍🎓

**Review by ivandeex — APPROVED** [review]
LGTM

**Comment by ivandeex** [comment]
Merging
@yedamao thank you
