### PR TITLE
copy/sync: fix bug on copying empty dirs

### LINKED ISSUE #2800: drive: rclone --dry-run will say it has to make (empty) directories that already exist
#### What is the problem you are having with rclone?
Empty directories are being correctly copied for some time now. With v1.45, --dry-run stopped creating these directories, correctly.
However, since v1.45, it will say "Not making directory as dry run is set" for directories that already exist in the destination.

#### What is your rclone version (output from `rclone version`)
v1.45

Haven't tried the github version because nothing on the log indicated any related change

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Linux 64bits

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone -v --dry-run --track-renames sync drive:dir1 drive2:dir2

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
(the following log was edited to remove lots and lots of file references and make it more readable)

2018/11/28 17:48:24 DEBUG : rclone: Version "v1.45" starting with parameters ["rclone" "-vv" "--dry-run" "--track-renames" "sync" "drive1:dir1" "drive2:/dir1"]
2018/11/28 17:48:24 DEBUG : Using config file from "/root/.rclone.conf"
2018/11/28 17:48:27 DEBUG : CRONOGRAMA/file1.pdf: Size and modification time the same (differ by 0s, within tolerance 1ms)
2018/11/28 17:48:27 DEBUG : CRONOGRAMA/file1.pdf: Unchanged skipping
2018/11/28 17:48:27 DEBUG : CRONOGRAMA/file2.pdf: Size and modification time the same (differ by 0s, within tolerance 1ms)
2018/11/28 17:48:27 DEBUG : CRONOGRAMA/file2.pdf: Unchanged skipping
2018/11/28 17:48:27 DEBUG : pacer: Rate limited, sleeping for 1.816067251s (1 consecutive low level retries)
2018/11/28 17:48:27 DEBUG : pacer: low level retry 1/10 (error googleapi: Error 403: User Rate Limit Exceeded. Rate of requests for user exceed configured project quota. You may consider re-evaluating expected per-user traffic to the API and adjust project quota limits accordingly. You may monitor aggregate quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=202264815644, userRateLimitExceeded)
2018/11/28 17:48:27 DEBUG : pacer: Rate limited, sleeping for 2.56224649s (2 consecutive low level retries)
2018/11/28 17:48:27 DEBUG : pacer: low level retry 2/10 (error googleapi: Error 403: User Rate Limit Exceeded. Rate of requests for user exceed configured project quota. You may consider re-evaluating expected per-user traffic to the API and adjust project quota limits accordingly. You may monitor aggregate quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=202264815644, userRateLimitExceeded)
2018/11/28 17:48:27 DEBUG : pacer: Resetting sleep to minimum 10ms on success
(... several entries removed ...)
( "- UPDATE ON 11／27" wasn't mentioned on any of the removed lines )
2018/11/28 17:48:31 INFO  : Google drive root '/dir1': Finished making map for --track-renames
2018/11/28 17:48:31 INFO  : Google drive root '/dir1': Waiting for checks to finish
2018/11/28 17:48:31 INFO  : Google drive root '/dir1': Waiting for renames to finish
2018/11/28 17:48:31 INFO  : Google drive root '/dir1': Waiting for transfers to finish
2018/11/28 17:48:31 NOTICE: - UPDATE ON 11／27: Not making directory as dry run is set
2018/11/28 17:48:31 DEBUG : Google drive root '/dir1': copied 1 directories
2018/11/28 17:48:31 INFO  : Waiting for deletions to finish
2018/11/28 17:48:31 INFO  :
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 0
Checks:               112 / 112, 100%
Transferred:            0 / 0, -
Elapsed time:        6.5s

2018/11/28 17:48:31 DEBUG : 35 go routines active
2018/11/28 17:48:31 DEBUG : rclone: Version "v1.45" finishing with parameters ["rclone" "-vv" "--dry-run" "--track-renames" "sync" "drive1:dir1" "drive2:/dir1"]

### PR DESCRIPTION
**Pull request by ishuah**
Sync/copy now only creates empty directories when they don't exist on the remote (--create-empty-src-dirs flag) - fixes #2800

#### What is the purpose of this change?

sync/copy now only create empty source directories on dst when they do not exist.

#### Was the change discussed in an issue or in the forum before?

Yes, this is issue #2800

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [x] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

File: fs/sync/sync.go [hunk 1]
```diff
@@ -876,6 +876,10 @@ func (s *syncCopyMove) Match(ctx context.Context, dst, src fs.DirEntry) (recurse
 			s.processError(err)
 		}
 	case fs.Directory:
+		// Only record matched (src & dst) empty dirs when performing move
+		if !s.DoMove {
```
Comment (ncw) [inline fs/sync/sync.go]: This has skipped the `errors.New("can't overwrite file with directory")` test below for sync & copy.

I think the test should probably be just around the src directory recording so after the `if ok`

Comment (ishuah) [reply fs/sync/sync.go]: That makes more sense! I've updated my PR.

**Comment by ishuah** [comment]
GolangCI timed out while processing. Is there any way of restarting the process? @ncw

**Comment by ncw** [comment]
I cant see any buttons to press to restart GolangCI!

The linux build runs golangci-lint too so the code is definitely OK :-)

I'll merge this now - thank you very much :-)
