### PR TITLE
mega: fix tls handshake failure - fixes #8565

### LINKED ISSUE #8565: [BUG] MEGA storage: remote error: tls: handshake failure
#### The associated forum post URL from `https://forum.rclone.org`
https://forum.rclone.org/t/remote-error-tls-handshake-failure-with-v1-69-2/51100

#### What is the problem you are having with rclone?
when using `use_https = true` , rclone doesnt work anymore with mega.
It returns `remote error: tls: handshake failure`

#### What is your rclone version (output from `rclone version`)
problem started with **v1.69.2**, persisted in **v1.69.3** 

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Debian bookworm 

#### Which cloud storage system are you using? (e.g. Google Drive)
MEGA

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
rclone copy mega:FILE.txt . -Pvv

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
` remote error: tls: handshake failure`

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

### PR DESCRIPTION
**Pull request by necaran**
#### What is the purpose of this change?

Fixes #8565

#### Was the change discussed in an issue or in the forum before?

https://github.com/rclone/rclone/issues/8565

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [ ] I have added tests for all changes in this PR if appropriate.
- [ ] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

File: backend/mega/mega.go [hunk 1]
```diff
@@ -216,7 +218,40 @@ func NewFs(ctx context.Context, name, root string, m configmap.Mapper) (fs.Fs, e
...
-		srv = mega.New().SetClient(fshttp.NewClient(ctx))
+		// srv = mega.New().SetClient(fshttp.NewClient(ctx))
+
+		// Workaround for Mega's use of insecure cipher suites which are no longer supported by default since Go 1.22.
+		// Relevent issues:
+		// https://github.com/rclone/rclone/issues/8565
+		// https://github.com/meganz/webclient/issues/103
+		clt := fshttp.NewClient(ctx)
+		clt.Transport = fshttp.NewTransportCustom(ctx, func(t *http.Transport) {
+			t.TLSClientConfig.CipherSuites = []uint16{
```
Comment (ncw) [inline backend/mega/mega.go]: Rather than hard coding Go's default ciphers, you can read them like this

```go
import "crypto/tls"

func cipherIDs() []uint16 {
    var ids []uint16
    // Read default ciphers
    for _, cs := range tls.CipherSuites() {
        ids = append(ids, cs.ID)
    }
    // Insecure but Mega uses TLS_RSA_WITH_AES_128_GCM_SHA256 for storage endpoints
    // (e.g. https://gfs302n114.userstorage.mega.co.nz) as of June 18, 2025.
    ids = append(ids, tls.TLS_RSA_WITH_AES_128_GCM_SHA256)
    return ids
}

// … later …
t.TLSClientConfig.CipherSuites = cipherIDs()
```

**Review by ncw — CHANGES_REQUESTED** [review]
This looks like a good fix - thank you.

I put a suggestion inline on how not to duplicate the Go default ciphers.

There is a lint to fix also.

Thanks
