### PR TITLE
bisync: fix handling of unreadable lockfiles - fixes #9290

### LINKED ISSUE #9290: bisync: garbled lockfiles will (almost) never expire
In one of our regular sync jobs, i found a garbled lockfile:

```
PS> Format-Hex foo.lck
(...)
           00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F
00000000   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
00000010   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
(...)
```

rclone reports a parse error but continues doing calculations on zero-initialized time-objects, leading to the lockfile expiring very far in the future:

```
2026-03-22 05:28:37 ERROR : C:\rclone\foo.lck: err: invalid character '\x00' looking for beginning of value
2026-03-22 05:28:37 INFO  : C:\rclone\foo.lck: Valid lock file found. Expires at 0001-01-01 00:00:00 +0000 UTC. (2562047h47m16.854775807s from now)
2026-03-22 05:28:37 INFO  : Lockfile info: 
2026-03-22 05:28:37 {
2026-03-22 05:28:37   "Session": "",
2026-03-22 05:28:37   "PID": "",
2026-03-22 05:28:37   "TimeRenewed": "0001-01-01T00:00:00Z",
2026-03-22 05:28:37   "TimeExpires": "0001-01-01T00:00:00Z"
2026-03-22 05:28:37 }
```

A parse error of the lockfile contents could be treated as an expired lockfile:

```
cmd/bisync/lockfile.go
----------------------
func (b *bisyncRun) lockFileIsExpired() bool {
	if b.lockFile != "" && bilib.FileExists(b.lockFile) {
		rdf, err := os.Open(b.lockFile)
		b.handleErr(b.lockFile, "error reading lock file", err, true, true)
		dec := json.NewDecoder(rdf)
		for {
			if err := dec.Decode(&b.lockFileOpt.data); err != nil {
				if err != io.EOF {
					fs.Errorf(b.lockFile, "err: %v", err)
					return true  <------------------- possible fix
					(...)
```

### PR DESCRIPTION
**Pull request by majiayu000**
#### What is the purpose of this change?

Fixes #9290

`lockFileIsExpired()` panics or fails permanently when a lockfile contains garbled (non-JSON) content, e.g. from a crash during write. This patch captures the JSON decode error and handles it based on `--max-lock`:

- `--max-lock > 0`: log a warning, treat the garbled lockfile as expired (the creator likely crashed), mark listings as failed, return true.
- `--max-lock 0` (default): log an error telling the user the lockfile needs manual inspection, return false.

The existing path for valid JSON lockfiles is unchanged.

#### Was the change discussed in an issue or in the forum before?

Yes, #9290. The approach follows nielash's stated design where `--max-lock > 0` implies the user accepts auto-expiration.

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [x] I have added tests for all changes in this PR if appropriate.
- [ ] I have added documentation for the changes if appropriate.
- [ ] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [ ] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

File: cmd/bisync/lockfile.go [hunk 1]
```diff
@@ -98,15 +98,26 @@ func (b *bisyncRun) lockFileIsExpired() bool {
...
-					fs.Errorf(b.lockFile, "err: %v", err)
+					decodeErr = err
 				}
 				break
 			}
 		}
 		b.handleErr(b.lockFile, "error closing file", rdf.Close(), true, true)
+		if decodeErr != nil {
+			if b.opt.MaxLock < basicallyforever {
+				fs.Infof(b.lockFile, Color(terminal.YellowFg, "Lock file is garbled (decode error: %v) and --max-lock is set. Treating as expired."), decodeErr)
```
Comment (nielash) [inline cmd/bisync/lockfile.go]: I would suggest changing "garbled" to "unreadable" or "invalid", as there are other possible reasons json decoding could fail.

File: cmd/bisync/lockfile.go [hunk 2]
```diff
@@ -98,15 +98,26 @@ func (b *bisyncRun) lockFileIsExpired() bool {
...
+				markFailed(b.listing1)
+				markFailed(b.listing2)
+				return true
+			}
+			fs.Errorf(b.lockFile, Color(terminal.RedFg, "Lock file is garbled (decode error: %v). Cannot determine expiration. Manual inspection required."), decodeErr)
```
Comment (nielash) [inline cmd/bisync/lockfile.go]: Same comment about "garbled", and also, I'm not sure that "expiration" makes sense here. If `b.opt.MaxLock >= basicallyforever` (which it must be here), expiration is disabled and we care only about whether or not a lockfile exists. So, it would suffice to say something like "Lock file exists, but contents are unreadable. (decode error: %v)"

File: cmd/bisync/lockfile_test.go [hunk 3]
```diff
@@ -0,0 +1,80 @@
...
+	"path/filepath"
+	"testing"
+	"time"
+
+	"github.com/rclone/rclone/fs"
+	"github.com/stretchr/testify/assert"
+	"github.com/stretchr/testify/require"
+)
+
+func newTestBisyncRun(t *testing.T, lockContent string, maxLock fs.Duration) *bisyncRun {
```
Comment (nielash) [inline cmd/bisync/lockfile_test.go]: I would suggest renaming this function to avoid confusion with the main bisync test suite in `cmd/bisync/bisync_test.go`. Add "Lockfile" somewhere maybe?

File: cmd/bisync/lockfile.go (hunk 1 above)
Comment (majiayu000) [reply cmd/bisync/lockfile.go]: done, switched to "unreadable" everywhere

File: cmd/bisync/lockfile.go (hunk 2 above)
Comment (majiayu000) [reply cmd/bisync/lockfile.go]: right, that makes more sense. changed to just report the unreadable state without mentioning expiration

File: cmd/bisync/lockfile_test.go (hunk 3 above)
Comment (majiayu000) [reply cmd/bisync/lockfile_test.go]: good call, renamed to `newTestLockfileBisyncRun` and the test functions to `TestLockfileIsExpired_*`

**Review by nielash — APPROVED** [review]
Great changes, thank you. 🙂 

This looks good to me now. (The lint check failure is unrelated.)
