### PR TITLE
Remote name fix

### LINKED ISSUE #6618: Can't add UTF-8 characters to alias names
Hello, 
Happy we have 
`rclone backend drives -o config gdrive:`
for list all shared drive for config file, but my shared drive have utf-8 char, and with large folder with char "_" very hard to read.
To much char "_" to very confuse, 

I have > 1000 shared drive, so it very confuse, hope a people help do that
folder rclone support utf-8 very great

image

Thank you very much

### PR DESCRIPTION
**Pull request by albertony**
#### What is the purpose of this change?

Main purpose is to ensure `rclone backend drives` command produces valid remote names. To fix #6618 we recently opened for Unicode characters, but there was one remaining issue when shared drive had space at end.

To fix this I refactored the regex that replaces character sequences invalid in remote names - from the drive backend code, and into the fspath code - where it is together with the main regex for validating config/remote names. Less risk of getting out of sync.

In addition, I refactored the existing check making remote names with leading `-` invalid, which was done as part of #4261. The existing check was done in `CheckConfigName` only, it was not considered by `checkRemoteName`. I'm pretty sure this has to be a small mistake? I fixed this by moving the check for leading `-` into the regex instead of being a separate check.

#### Was the change discussed in an issue or in the forum before?

#6618

#### Checklist

- [X] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [X] I have added tests for all changes in this PR if appropriate.
- [ ] I have added documentation for the changes if appropriate.
- [X] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [X] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

File: fs/fspath/path_test.go [hunk 1]
```diff
@@ -19,34 +19,38 @@ var (
 
 func TestCheckConfigName(t *testing.T) {
```
Comment (ncw) [inline fs/fspath/path_test.go:20]: You appear to have overwritten this test instead of making a new one?

Comment (albertony) [reply fs/fspath/path_test.go:20]: Yes, I extended the `TestCheckConfigName` test by simply adding a second "result" value and using the same input to test both `CheckConfigName` and `MakeConfigName` (should probably have renamed the test). This to avoid another "currently-identical-soon-just-almost-identical" copy of all the input strings - like there to some degree already is in the separate `TestCheckRemoteName`. But I could split it into a separate test, duplicating the same input, if you think that is better, that is completely fine as well..?

**Review by ncw — APPROVED** [review]
I think this looks great, please merge when you are ready.
