### PR TITLE
fs rc: fixes incorrect Content-Type in HTTP API - fixes #7726

### LINKED ISSUE #7726: Wrong Content-Type in HTTP API
#### The associated forum post URL from `https://forum.rclone.org`
https://forum.rclone.org/t/wrong-content-type-in-http-api/45420

#### What is the problem you are having with rclone?
The [HTTP API](https://rclone.org/rc/#api-http) always returns the Content-Type `text/plain; charset=utf-8` instead of `application/json`.

#### What is your rclone version (output from `rclone version`)
```
rclone v1.66.0
- os/version: alpine 3.19.1 (64 bit)
- os/kernel: 5.15.0-101-generic (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.22.1
- go/linking: static
- go/tags: none
```

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Windows and Linux (Docker), both 64 bit

#### Which cloud storage system are you using? (e.g. Google Drive)
Not relevant

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
`curl -v -X POST http://localhost:5572/core/stats`

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
```
rclone    | 2024/04/03 22:49:45 DEBUG : rclone: Version "v1.66.0" starting with parameters ["rclone" "rcd" "--rc-addr" ":5572" "--rc-no-auth" "-vv"]
rclone    | 2024/04/03 22:49:45 NOTICE: Serving remote control on http://[::]:5572/
rclone    | 2024/04/03 22:49:56 DEBUG : rc: "core/stats": with parameters map[]
rclone    | 2024/04/03 22:49:56 DEBUG : rc: "core/stats": reply map[bytes:0 checks:0 deletedDirs:0 deletes:0 elapsedTime:10.985591033 errors:0 eta:<nil> fatalError:false renames:0 retryError:false serverSideCopies:0 serverSideCopyBytes:0 serverSideMoveBytes:0 serverSideMoves:0 speed:0 totalBytes:0 totalChecks:0 totalTransfers:0 transferTime:0 transfers:0]: <nil>
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

### PR DESCRIPTION
**Pull request by KDreynolds**
#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [x] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

File: fs/rc/rcserver/rcserver.go [hunk 1]
```diff
@@ -201,6 +201,7 @@ func writeError(path string, in rc.Params, w http.ResponseWriter, err error, sta
 	fs.Errorf(nil, "rc: %q: error: %v", path, err)
 	params, status := rc.Error(path, in, err, status)
 	w.WriteHeader(status)
+	w.Header().Set("Content-Type", "application/json")
```
Comment (ncw) [inline fs/rc/rcserver/rcserver.go:204]: I think that this line needs to be before the `w.WriteHeader`

File: fs/rc/rcserver/rcserver_test.go [hunk 2]
```diff
@@ -847,3 +847,22 @@ func TestServeModTime(t *testing.T) {
 	}}
 	testServer(t, tests, &opt)
 }
+
+func TestContentTypeJSON(t *testing.T) {
+	tests := []testRun{
+		{
+			Name:        "Check Content-Type for JSON response",
+			URL:         "rc/noop", // Assuming rc/noop returns JSON
```
Comment (ncw) [inline fs/rc/rcserver/rcserver_test.go:855]: You should be able to test the error case with `rc/error` - I'd suggest another test for that.

**Review by ncw — COMMENTED** [review]
Looking good!

I think the error case needs fixing though and needs a test - see inline.

Formatting good according to the CI.

Thank you :-)

File: fs/rc/rcserver/rcserver_test.go (hunk 2 above)
Comment (KDreynolds) [reply fs/rc/rcserver/rcserver_test.go]: Ok I added another test case for rc/error, good chance I did something in an odd way, lmk

File: fs/rc/rcserver/rcserver_test.go [hunk 3]
```diff
@@ -847,3 +848,76 @@ func TestServeModTime(t *testing.T) {
...
+			Headers: map[string]string{
+				"Content-Type": "application/json",
+			},
+		},
+	}
+	opt := newTestOpt()
+	testServer(t, tests, &opt)
+}
+
+func TestErrorContentTypeJSON(t *testing.T) {
```
Comment (ncw) [inline fs/rc/rcserver/rcserver_test.go:871]: Couldn't this test just be another test case in ` TestContentTypeJSON`? I'm probably missing something as to why not...

If not I suggest you add a new feature to the testServer rather than duplicating it below. By that I mean add a new flag to `testRun`, set it in the test case, and use it to control the changes you need in `testServer`. That will make for much neater and more maintainable code.

File: fs/rc/rcserver/rcserver_test.go [hunk 4]
```diff
@@ -847,3 +848,76 @@ func TestServeModTime(t *testing.T) {
...
+		t.Run(tc.Name, func(t *testing.T) {
+			req, err := http.NewRequest(tc.Method, tc.URL, nil)
+			require.NoError(t, err)
+
+			rr := httptest.NewRecorder()
+			handler := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
+				// Simulate setting the error response in your actual handler
+				w.Header().Set("Content-Type", "application/json")
+				w.WriteHeader(tc.ExpectedStatus)
+				w.Write([]byte(tc.ExpectedJSON)) // This should be replaced with the actual error handling logic
```
Comment (ncw) [inline fs/rc/rcserver/rcserver_test.go:905]: The linter says this is missing an error check. `w.Write` returns a length and error if I remember correctly, so you'd check it something like this

```go
_, err := w.Write(...)
require.NoError(t, err)
```

**Review by ncw — COMMENTED** [review]
Thank you :-)

Please see inline comments.

**Comment by KDreynolds** [comment]
not exactly sure why the mac amd build failed. 
Hopefully these changes work and are coherent. 
Thanks!

**Review by ncw — APPROVED** [review]
That looks very nice now.

I like your approach normalizing the JSON.

The mac test failed due to a known flakey test not your code, so I will merge this now thank you :-)

**Comment by KDreynolds** [comment]
Thank you! Appreciate it!

**Comment by ncw** [comment]
@KDreynolds I appreciate your contributions and I enjoy helping you with them, so keep them coming :-)

**Comment by nullinger** [comment]
Thank you, @KDreynolds  and @ncw !
