### PR TITLE
config: reject remote names starting with a dash. (#4261)

### LINKED ISSUE #4261: Disallow remotes beginning with dash in a backwards compatible way
#### What is the problem you are having with rclone?
Can't use remotes beginning with the character `-`.
 
#### What is your rclone version (output from `rclone version`)
```
rclone v1.51.0
- os/arch: linux/amd64
- go version: go1.13.7
```

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Fedora 32

####  Which cloud storage system are you using? (eg Google Drive)
Any

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
`rclone lsf -my-remote-:` or `rclone lsf "-my-remote-:"`

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
```
Error: unknown shorthand flag: 'm' in -my-remote-:
Usage:
  rclone lsf remote:path [flags]

Flags:
      --absolute           Put a leading / in front of path names.
      --csv                Output in CSV format.
  -d, --dir-slash          Append a slash to directory names. (default true)
      --dirs-only          Only list directories.
      --files-only         Only list files.
  -F, --format string      Output format - see  help for details (default "p")
      --hash h             Use this hash when h is used in the format MD5|SHA-1|DropboxHash (default "MD5")
  -h, --help               help for lsf
  -R, --recursive          Recurse into the listing.
  -s, --separator string   Separator for the items in the format. (default ";")

Use "rclone [command] --help" for more information about a command.
Use "rclone help flags" for to see the global flags.
Use "rclone help backends" for a list of supported services.

2020/05/20 22:46:47 Fatal error: unknown shorthand flag: 'm' in -my-remote-:
```

### PR DESCRIPTION
**Pull request by jtagcat**
I have briefly looked at go (and familiarized myself with it) before, this is the first actually useful piece of code I have written with go. In total, it took 3 hours for this tiny piece of code. A bit of remind go, a casual (hackathon mode: <5m) 30-40m in this tiny piece, more time than I'd like in getting the environment ready (mainly [cloning to the wrong location the wrong way](https://github.com/rclone/rclone/issues/4261#issuecomment-644315664)), 10m to install go (the recommended way is to get a tar and never update, what I don't agree to, returned to my package manager and also added it to my script of run-this-after-reinstall), ~45 in general adding to documentation.  :tada: 

#### What is the purpose of this change?

Disallow naming or renaming remotes beginning with a dash ( - ), as while operating normally, you can't have flags after the remote and must use `--` between the flags and the remote(s), what might confuse people, whose first-in-life remote (assuming little cli experience) usage might get confusing, frustrating; possibly leading to opting for an rclone alternative.

Already named remotes are unaffected. Hardcore i-want-to-name-my-remotes-starting-with-dashes-and-give-me-less-flexibility users can still (re)name the remotes by editing the config file manually.

#### Was the change discussed in an issue or in the forum before?

Closes #4261 

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [x] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by jtagcat** [comment]
:thinking: builds succeeded on fork: https://github.com/jtagcat/rclone/actions/runs/136387083

File: fs/fspath/path.go [hunk 1]
```diff
@@ -36,6 +37,10 @@ func CheckConfigName(configName string) error {
 	if !configNameMatcher.MatchString(configName) {
 		return errInvalidCharacters
 	}
+	// Reject configName, if it starts with -, complicates usage. (#4261)
+	if strings.HasPrefix(configName, "-") {
```
Comment (ncw) [inline fs/fspath/path.go:41]: Can you add a test for this here

https://github.com/rclone/rclone/blob/17d5a724164bdbf22ca3118c38fca39dddaebd9d/fs/fspath/path_test.go#L12

**Comment by ncw** [comment]
>  builds succeeded on fork: https://github.com/jtagcat/rclone/actions/runs/136387083

I think you got unlucky with #4171 - I fixed most of them last night I think so if you rebase on master you should get a clean CI run :crossed_fingers: (this isn't necessary though!)
