### PR TITLE
dlna: Fake out implementation of X_MS_MediaReceiverRegistrar.

### LINKED ISSUE #3502: Serve DLNA not working with RegisterDevice SOAP action
#### What is the problem you are having with rclone?

My older internet radio device doesn't want to connect to my rclone dlna server. From the log I can see there is some issue with "urn:microsoft.com:service:X_MS_MediaReceiverRegistrar:1RegisterDevice" SOAP header causing my radio not to connect to the server.
Seems to be the same issue as reported to MiniDLNA here: [https://bugs.launchpad.net/ubuntu/+source/minidlna/+bug/1231886](https://bugs.launchpad.net/ubuntu/+source/minidlna/+bug/1231886)

#### What is your rclone version (output from `rclone version`)

rclone v1.49.1
- os/arch: linux/arm
- go version: go1.12.9

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Raspbian, 64 bit

####  Which cloud storage system are you using? (eg Google Drive)

Mega

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone serve dlna mega_test:

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

2019/09/01 21:22:08 DEBUG : rclone: Version "v1.49.1" starting with parameters ["rclone" "-vv" "serve" "dlna" "mega_test:"]
2019/09/01 21:22:08 DEBUG : Using config file from "/home/pi/.config/rclone/rclone.conf"
2019/09/01 21:22:15 INFO  : mega root '': poll-interval is not supported by this remote
2019/09/01 21:22:15 DEBUG : Adding path "vfs/forget" to remote control registry
2019/09/01 21:22:15 DEBUG : Adding path "vfs/refresh" to remote control registry
2019/09/01 21:22:15 DEBUG : Adding path "vfs/poll-interval" to remote control registry
2019/09/01 21:22:15 NOTICE: mega root '': Serving HTTP on [::]:7879
2019/09/01 21:22:15 INFO  : DLNA server on :7879: Started SSDP on wlan0
2019/09/01 21:22:15 INFO  : DLNA server on :7879: Started SSDP on eth0
2019/09/01 21:22:16 INFO  : /static/ContentDirectory.xml: 192.168.1.221:51378 GET 200  %!s(<nil>)
2019/09/01 21:22:16 INFO  : /static/ConnectionManager.xml: 192.168.1.221:51378 GET 200  %!s(<nil>)
2019/09/01 21:22:16 INFO  : /static/X_MS_MediaReceiverRegistrar.xml: 192.168.1.221:51378 GET 200  %!s(<nil>)
2019/09/01 21:22:16 ERROR : /: 192.168.1.221:51380 SUBSCRIBE 404  %!s(<nil>)
2019/09/01 21:22:16 ERROR : /: 192.168.1.221:51379 SUBSCRIBE 404  %!s(<nil>)
2019/09/01 21:22:16 INFO  : /ctl: 192.168.1.221:51378 POST 200 "urn:schemas-upnp-org:service:ContentDirectory:1#GetSearchCapabilities" %!s(<nil>)
2019/09/01 21:22:16 INFO  : /ctl: 192.168.1.221:51378 POST 200 "urn:schemas-upnp-org:service:ContentDirectory:1#Browse" %!s(<nil>)
2019/09/01 21:22:17 INFO  : /ctl: 192.168.1.221:51378 POST 200 "urn:schemas-upnp-org:service:ContentDirectory:1#Browse" %!s(<nil>)
2019/09/01 21:22:18 INFO  : /ctl: 192.168.1.221:51378 POST 200 "urn:schemas-upnp-org:service:ContentDirectory:1#Browse" %!s(<nil>)
2019/09/01 21:22:19 INFO  : /ctl: 192.168.1.221:51378 POST 200 "urn:schemas-upnp-org:service:ContentDirectory:1#Browse" %!s(<nil>)
2019/09/01 21:22:20 INFO  : /ctl: 192.168.1.221:51378 POST 200 "urn:schemas-upnp-org:service:ContentDirectory:1#Browse" %!s(<nil>)
2019/09/01 21:22:21 INFO  : /ctl: 192.168.1.221:51378 POST 200 "urn:schemas-upnp-org:service:ContentDirectory:1#Browse" %!s(<nil>)
2019/09/01 21:22:22 INFO  : /ctl: 192.168.1.221:51378 POST 200 "urn:schemas-upnp-org:service:ContentDirectory:1#Browse" %!s(<nil>)
2019/09/01 21:22:23 INFO  : /ctl: 192.168.1.221:51378 POST 200 "urn:schemas-upnp-org:service:ContentDirectory:1#Browse" %!s(<nil>)
2019/09/01 21:22:24 INFO  : /ctl: 192.168.1.221:51378 POST 200 "urn:schemas-upnp-org:service:ContentDirectory:1#Browse" %!s(<nil>)
2019/09/01 21:22:25 INFO  : /ctl: 192.168.1.221:51378 POST 200 "urn:schemas-upnp-org:service:ContentDirectory:1#Browse" %!s(<nil>)
2019/09/01 21:22:26 INFO  : /ctl: 192.168.1.221:51378 POST 200 "urn:schemas-upnp-org:service:ContentDirectory:1#Browse" %!s(<nil>)
2019/09/01 21:22:27 INFO  : /ctl: 192.168.1.221:51378 POST 200 "urn:schemas-upnp-org:service:ContentDirectory:1#Browse" %!s(<nil>)
2019/09/01 21:22:28 INFO  : /ctl: 192.168.1.221:51378 POST 200 "urn:schemas-upnp-org:service:ContentDirectory:1#Browse" %!s(<nil>)
2019/09/01 21:22:29 ERROR : DLNA server on :7879: Could not parse SOAPACTION header: urn:microsoft.com:service:X_MS_MediaReceiverRegistrar:1
2019/09/01 21:22:29 ERROR : /ctl: 192.168.1.248:2008 POST 500 "urn:microsoft.com:service:X_MS_MediaReceiverRegistrar:1#IsAuthorized" %!s(<nil>)
2019/09/01 21:22:29 INFO  : /ctl: 192.168.1.221:51378 POST 200 "urn:schemas-upnp-org:service:ContentDirectory:1#Browse" %!s(<nil>)

### PR DESCRIPTION
**Pull request by sretlawd**
Using the same responses as minidlna.

Fixes #3502.

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [x] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

File: cmd/serve/dlna/mrrs.go [hunk 1]
```diff
@@ -0,0 +1,26 @@
+package dlna
+
+import (
+	"github.com/anacrolix/dms/upnp"
```
Comment (golangcibot) [inline cmd/serve/dlna/mrrs.go]: File is not `goimports`-ed (from `goimports`)
```suggestion

```

File: cmd/serve/dlna/dlna_test.go [hunk 2]
```diff
@@ -1,8 +1,10 @@
 package dlna
 
 import (
+	"bytes"
 	"context"
 	"fmt"
+	"github.com/anacrolix/dms/soap"
```
Comment (golangcibot) [inline cmd/serve/dlna/dlna_test.go]: File is not `goimports`-ed (from `goimports`)
```suggestion

```

File: cmd/serve/dlna/mrrs.go (hunk 1 above)
Comment (sretlawd) [reply cmd/serve/dlna/mrrs.go]: This is definitely used, not sure why the bot is complaining?

**Comment by ncw** [comment]
The CI failed with this

```
-- START CODE QUALITY REPORT -------------------------------
cmd/serve/dlna/mrrs.go:4: File is not `goimports`-ed (goimports)
	"github.com/anacrolix/dms/upnp"
cmd/serve/dlna/dlna_test.go:7: File is not `goimports`-ed (goimports)
	"github.com/anacrolix/dms/soap"
Makefile:68: recipe for target 'check' failed
make: *** [check] Error 1
The command "make check" exited with 2.
```

This should fix it

```
gofmt -w cmd/serve/dlna/mrrs.go
gofmt -w cmd/serve/dlna/dlna_test.go
```

File: cmd/serve/dlna/mrrs.go [hunk 3]
```diff
@@ -0,0 +1,26 @@
+package dlna
+
+import (
+	upnp "github.com/anacrolix/dms/upnp"
```
Comment (golangcibot) [inline cmd/serve/dlna/mrrs.go]: File is not `goimports`-ed (from `goimports`)
```suggestion

```

File: cmd/serve/dlna/dlna_test.go [hunk 4]
```diff
@@ -1,8 +1,10 @@
 package dlna
 
 import (
+	"bytes"
 	"context"
 	"fmt"
+	soap "github.com/anacrolix/dms/soap"
```
Comment (golangcibot) [inline cmd/serve/dlna/dlna_test.go]: File is not `goimports`-ed (from `goimports`)
```suggestion

```

**Comment by sretlawd** [comment]
gofmt didn't work, but installed goimports via `go get -u golang.org/x/tools/cmd/goimports` and that did the trick.

**Comment by ncw** [comment]
I fixed the merge conflict.. assuming the tests pass I'll merge it :-)

**Comment by ncw** [comment]
LGTM - thank you :-)
