### PR TITLE
nfsmount: fix writing files via Finder on macOS (and other bugs) - fixes #7503

### LINKED ISSUE #7503: nfsmount — not functional on macOS for writing files to OneDrive via Finder
**Hello! I'm writing with an active issue that seems to affect `rclone nfsmount` on macOS.**

-----

#### The associated forum post URL from `https://forum.rclone.org`

https://forum.rclone.org/t/rclone-v1-65-0-release/43100/25?u=scuba-tech

#### What is the problem you are having with rclone?

**ALL** attempts to copy files of any size or type, from Finder into OneDrive, via `nfsmount` fail. 

It is not possible to write from Finder or save work. It *is* possible to read/open files.

Simple writing operations like `touch` and `cat > filename` from a shell do write properly into nfsmount.

-----

#### What is your rclone version (output from `rclone version`)

1.65.0 via brew

-----

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

**macOS Sonoma (14.1.1)** // ARM64

-----

#### Which cloud storage system are you using? (e.g. Google Drive)

Microsoft OneDrive (personal family // 6TB)

-----

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

`rclone nfsmount --vfs-cache-mode full --filter-from "/Users/<user>/.config/rclone/rclone-filter-rules.txt" OD: ~/MOUNT-OneDrive --verbose`

Notes:

1. I am using `--vfs-cache-mode full` to allow writing with OneDrive. Using none gives an (expected) read-only error message.
2. Here are the contents of my filter rules file:

```
- **/.DS_Store
- **/.hidden*
- **/._*
```

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

```
[ERROR] No file for lookup of ._GH010215.mp4
[ERROR] call to 0x106<###>  failed: No such file or directory
INFO  : SdT-Inboxes/GH010215.mp4: vfs cache: removed cache file as file deleted
[ERROR] No file for lookup of ._7F2A7976.JPG
[ERROR] call to 0x106<###>  failed: No such file or directory
[ERROR] err loading attrs for SdT-Inboxes/GH010215.mp4: file does not exist
[ERROR] No file for lookup of ._7F2A7977.JPG
[ERROR] call to 0x106<###>  failed: No such file or directory
[ERROR] err loading attrs for SdT-Inboxes/GH010215.mp4: file does not exist
```

image

Confirming that the copy into the mount _did fail_, checking with Finder, `ls -hAls`, and even OneDrive webUI... all of these confirm that the file does **not** actually "already exist" as the error message above claims!

I hope this report helps with getting `nfsmount` sorted. :) 

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

### PR DESCRIPTION
**Pull request by nielash**
#### What is the purpose of this change?

This fixes a critical bug in `nfsmount` / `serve nfs` on macOS (#7503), and also fixes two more minor bugs (effective deadlock on external unmounting, and `--volname` being ignored). 

#### Was the change discussed in an issue or in the forum before?

- #7503 
- https://forum.rclone.org/t/rclone-v1-65-0-release/43100/25?u=scuba-tech
- https://forum.rclone.org/t/how-to-use-nfs-mount-on-macos-sonoma/44203/3?u=nielash
- #7072

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [x] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

File: cmd/serve/nfs/handler.go [hunk 1]
```diff
@@ -50,17 +57,23 @@ func (h *BackendAuthHandler) FSStat(ctx context.Context, f billy.Filesystem, s *
...
-func (h *BackendAuthHandler) FromHandle([]byte) (billy.Filesystem, []string, error) {
-	return nil, []string{}, nil
+func (h *BackendAuthHandler) FromHandle(b []byte) (billy.Filesystem, []string, error) {
+	return h.cache.FromHandle(b)
 }
 
 // HandleLimit handled by cachingHandler
 func (h *BackendAuthHandler) HandleLimit() int {
-	return -1
+	if h.vfs.Opt.CacheMaxSize < 0 {
```
Comment (ncw) [inline cmd/serve/nfs/handler.go:71]: I don't like the re-using of --vfs-cache-max-size here as the parameter...

I'd suggest making an extra flag for `cmd/serve/nfs` - it has one already add another?

**Review by ncw — COMMENTED** [review]
I think this looks great - good work :-)

I don't like the re-use of the --vfs-cache-max-size parameter though - see suggestion inline.

Thank you :-)

File: cmd/serve/nfs/handler.go (hunk 1 above)
Comment (nielash) [reply cmd/serve/nfs/handler.go]: Made this change 👍

**Review by ncw — APPROVED** [review]
Looks great now 🙂

Please merge.
