### PR TITLE
fs: improve log output when no changes are made - fixes #3454

### LINKED ISSUE #3454: Improve log output when no files / changes are needed
#### What is your current rclone version (output from `rclone version`)?
v1.48

#### What problem are you are trying to solve?

When calling rclone move (or similar commands) and there is nothing for rclone to upload, it prints this log:

```
2019/08/18 06:11:43 INFO  : Starting HTTP transaction limiter: max 10 transactions/s with burst 1
2019/08/18 06:11:43 INFO  : Google drive root '': Waiting for checks to finish
2019/08/18 06:11:43 INFO  : Google drive root '': Waiting for transfers to finish
2019/08/18 06:11:43 INFO  :
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 0
Checks:                 0 / 0, -
Transferred:            0 / 0, -
Elapsed time:          0s
```

This ends up being super confusing for users, they look at this and think something is wrong, when nothing is wrong. I've so far worked around it by doing a check on the number of files in the upload directory, but it's not ideal.

They find these lines in particular confusing `Google drive root '': Waiting for checks to finish`

#### How do you think rclone should be changed to solve that?
Instead of printing this zeroed out log entry, perhaps just print "No files were found that needed action for this operation" or something along those lines.

### PR DESCRIPTION
**Pull request by tgallant**
#### What is the purpose of this change?

The purpose of this change is to improve the log output for when no changes are made. This is accomplished by the following changes:

- changing a few log messages to debug level
- adding an info log message for when 0 bytes were transferred

Here is an example output:
```shell
~/go/src/rclone $ ./rclone -vv sync ~/src_folder/ ~/dst_folder/
2020/02/09 13:38:02 DEBUG : rclone: Version "v1.51.0-DEV" starting with parameters ["./rclone" "-vv" "sync" "/Users/tim/src_f
older/" "/Users/tim/dst_folder/"]                                                                                           
2020/02/09 13:38:02 NOTICE: Config file "/Users/tim/.config/rclone/rclone.conf" not found - using defaults
2020/02/09 13:38:02 DEBUG : Local file system at /Users/tim/dst_folder/: Waiting for checks to finish
2020/02/09 13:38:02 DEBUG : hi.txt: Size and modification time the same (differ by 0s, within tolerance 1ns)
2020/02/09 13:38:02 DEBUG : hi.txt: Unchanged skipping
2020/02/09 13:38:02 DEBUG : Local file system at /Users/tim/dst_folder/: Waiting for transfers to finish
2020/02/09 13:38:02 DEBUG : Waiting for deletions to finish
2020/02/09 13:38:02 INFO  : There was nothing to transfer
2020/02/09 13:38:02 INFO  : 
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Checks:                 1 / 1, 100%
Elapsed time:         0.0s

2020/02/09 13:38:02 DEBUG : 4 go routines active
2020/02/09 13:38:02 DEBUG : rclone: Version "v1.51.0-DEV" finishing with parameters ["./rclone" "-vv" "sync" "/Users/tim/src_
folder/" "/Users/tim/dst_folder/"]                                                                                                                                                                                     
```

#### Was the change discussed in an issue or in the forum before?

https://github.com/rclone/rclone/issues/3454

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [x] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

File: fs/sync/sync.go [hunk 1]
```diff
@@ -756,6 +756,10 @@ func (s *syncCopyMove) run() error {
 	// Read the error out of the context if there is one
 	s.processError(s.ctx.Err())
 
+	if accounting.Stats(s.ctx).GetBytes() == 0 {
```
Comment (ncw) [inline fs/sync/sync.go]: I think this should probably say `GetTransfers() == 0` just in case we are transferring 0 length files

**Comment by tgallant** [comment]
Thanks @ncw, updated!

**Comment by ncw** [comment]
Thank you for that, I'll merge that now :-)
