### PR TITLE
vfs: fix directory cache serving stale data

### LINKED ISSUE #6335: VFS doesn't update mtime for directories
#### What is the problem you are having with rclone?
I'm using `serve webdav` to serve a local directory over WebDAV. This works fine except that the VFS layer doesn't update the mtime (ModTime) of directories even after `dir-cache-time` has expired. Debugging revealed that the problem is in `dir.go:635` where rclone reuses `node` (which has the old modTime), `item` (the new value with the correct modTime) is just discarded.

I'm not familiar with the design principles of the rclone VFS layer so I'm not sure what the right fix here is.

#### What is your rclone version (output from `rclone version`)
Self-built from revision 2f461f13e3efe603bdd8fb4057f3e8242a59956f

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Linux x86_64

### PR DESCRIPTION
**Pull request by lorenz**
The VFS directory cache layer didn't update directory properties like the last modified time at all, as the new objects were not used. The same problem is already solved for files, implement the same solution for directories.

Fixes #6335

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [x] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Review by ncw — COMMENTED** [review]
That looks like a nice fix :-)

How did you come across the problem?

Can you make a test for it?

**Comment by lorenz** [comment]
I had WebDAV client software which cached directory contents if the modified time of a directory wasn't updated. This caused new data to never show up. Re Testing: I have pretty much no experience with the codebase. I'll happily write a test for it with a bit of guidance. Manual testing was done by serving a local directory with WebDAV, setting dir-cache-time=10s and touching a new file in the directory, then waiting for >10s and refreshing to see if the modified time changed.

**Comment by lorenz** [comment]
@ncw Anything I can do to get this merged? It's been sitting for 2.5 years and people are still running into the issue.

File: vfs/dir.go [hunk 1]
```diff
@@ -916,6 +918,17 @@ func (d *Dir) cachedNode(relativePath string) Node {
 	return node
 }
 
+// Update the object but don't update the directory cache - for use by
```
Comment (ncw) [inline vfs/dir.go:921]: I think this comment is wrong. It is certainly confusing me!

I think you mean something like this?

```go
// Update the directory in the directory cache with a new fs.Directory.
// For use by the directory cache.
// Does not update the VFS cache.
```

**Review by ncw — COMMENTED** [review]
@lorenz sorry for the loooong delay!

To merge first it needs rebasing on master.

Then ideally we'd have a test.

> Manual testing was done by serving a local directory with WebDAV, setting dir-cache-time=10s and touching a new file in the directory, then waiting for >10s and refreshing to see if the modified time changed

So we need to automate that. We don't need to serve it with WebDAV though - the test can just look at the VFS directly.

If you take a look in https://github.com/rclone/rclone/blob/master/vfs/dir_test.go you'll see lots of test which you could copy and adapt.

I think you can probably call `ForgetAll()` rather than waiting for the vfs cache to expire also.

Let me know if you need more help.

**Review by lorenz — COMMENTED** [review]
The original approach turned out to perform far too much work. The only problem is the `entry` field which doesn't get updated. Also this is now harder to reproduce as these stale entries get cleaned out after twice the invalidation period. But stale data can still persist indefinitely if it is frequently accessed, so this patch is still necessary.

Fixed all of this and added a test which fails without the fix.

**Comment by ncw** [comment]
Looks like the tests are failing under Windows.

The windows timers have lower granularity than other OSes which often causes stuff like this.

Can you use `ForgetAll()` rather than waiting for the vfs cache entry to time out?

**Comment by ncw** [comment]
> ForgetAll drops the direntry entirely. On next access it gets recreated, thus the bug doesn't happen. The behavior this is relying on (that the parent directory modtime gets updated when files are created/deleted) might also not be applicable to Windows.

I think this should happen.

Chat GPT came up with this table for whether a parent directory modtime gets updated or not. I veriefied the Windows line with my Windows VM

OS / FS | File Created | File Deleted | File Modified
-- | -- | -- | --
Linux (Ext4, XFS, Btrfs, etc.) | ✅ | ✅ | ❌
macOS (APFS, HFS+) | ✅ | ✅ | ❌
Windows (NTFS, FAT32, exFAT) | ✅ | ✅ | ❌
BSD (UFS, ZFS) | ✅ | ✅ | ❌
NFS / SMB | ⚠️ | ⚠️ | ❌

- ✅ = Updates modtime
- ❌ = Does not update modtime
-⚠️ = May depend on caching or implementation

Maybe you could repeat the failing `t.Error("ModTime not invalidated")` test until it succeeds or 10 times?

Something like
	

```go
        var ok bool
	for tries := 1; tries <= 10; tries++ {
            // ModTime of directory must be different after second file was written.
            ok = !modTime1.Equal(modTime2)
            if ok {
                break
            }
            time.Sleep(100*time.Millisecond)
	}
	if  !ok {
		t.Error("ModTime not invalidated")
	}
```

**Comment by lorenz** [comment]
Spun up a Windows 26001 (24H2) VM, this cannot be made reliable on Windows. The filesystem API (directly using os.Stat on the backing files) behaves erratically. Even waiting multiple seconds between writes sometimes ends up with no update to the last modified timestamp on the directory. Either we force the timestamp to be "correct" via a Windows-specific API or skip the entire test on Windows.

**Comment by ncw** [comment]
Ok let's skip the test on windows. I've noticed before that the VM filesystem is a bit erratic!

**Comment by lorenz** [comment]
Test is now getting skipped on Windows

**Review by ncw — APPROVED** [review]
Great - thank you :-)

I'll merge now.

**Comment by ncw** [comment]
Unfortunately this PR has generated a lot of failures in the [daily integration tests](https://pub.rclone.org/integration-tests/current/)

You'll see if you look at the link above that the new TestDirEntryModTimeInvalidation is failing.

Have you got time to take a look at this @lorenz ?

Thanks

**Comment by darthShadow** [comment]
I think this is failing because it's not skipping the test for remotes that don't support the `DirModTimeUpdatesOnWrite` feature. All the failing backends in the test suite seem to be those which are missing that feature.

**Comment by ncw** [comment]
I have attempted to fix the integration test failures in 0010090d0517976248894bbd48a9bb1ac5bc0182 :crossed_fingers:
