### PR TITLE
smb: add support for kerberos authentication

### LINKED ISSUE #7800: Cannot access SMB share via Kerberos
#### What is the problem you are having with rclone?

It seems rclone is using NTLM by default which has been disabled by our security team therefore I get a `couldn't connect SMB: response error: The attempted logon is invalid. This is either due to a bad username or authentication information.` error.

#### What is your rclone version (output from `rclone version`)
```config
# rclone version
rclone v1.61.1
- os/version: centos 7.9.2009 (64 bit)
- os/kernel: 3.10.0-1160.62.1.el7.x86_64 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.19.4
- go/linking: static
- go/tags: none
```

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

CentOS Linux release 7.9.2009 , 64 bits

#### Which cloud storage system are you using? (e.g. Google Drive)

SMB Share

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

```shell
# rclone --low-level-retries 1 ls myNAS-SMB:
2024/04/24 15:45:13 ERROR : : error listing: couldn't connect SMB: response error: The attempted logon is invalid. This is either due to a bad username or authentication information.
2024/04/24 15:45:13 Failed to ls with 2 errors: last error was: couldn't connect SMB: response error: The attempted logon is invalid. This is either due to a bad username or authentication information.
```

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

```shell
# rclone --low-level-retries 1 -vv ls myNAS-SMB:
2024/04/24 15:42:10 DEBUG : rclone: Version "v1.61.1" starting with parameters ["rclone" "--low-level-retries" "1" "-vv" "ls" "myNAS-SMB:"]
2024/04/24 15:42:10 DEBUG : Creating backend with remote "myNAS-SMB:"
2024/04/24 15:42:10 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
2024/04/24 15:42:10 DEBUG : pacer: low level retry 1/1 (error couldn't connect SMB: response error: The attempted logon is invalid. This is either due to a bad username or authentication information.)
2024/04/24 15:42:10 DEBUG : pacer: Rate limited, increasing sleep to 200ms
2024/04/24 15:42:10 ERROR : : error listing: couldn't connect SMB: response error: The attempted logon is invalid. This is either due to a bad username or authentication information.
2024/04/24 15:42:10 DEBUG : 4 go routines active
2024/04/24 15:42:10 Failed to ls with 2 errors: last error was: couldn't connect SMB: response error: The attempted logon is invalid. This is either due to a bad username or authentication information.
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

### PR DESCRIPTION
**Pull request by jgiannuzzi**
#### What is the purpose of this change?

Add support for kerberos authentication to the `smb` backend.

#### Was the change discussed in an issue or in the forum before?

Fixes #7800.

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [x] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by jgiannuzzi** [comment]
Hey @ncw, this is the PR I promised to add kerberos support to the `smb` backend. Could you please take a look?

File: fstest/testserver/init.d/TestSMBKerberos [hunk 1]
```diff
@@ -0,0 +1,74 @@
...
+USER=rclone
+DOMAIN=RCLONE
+REALM=RCLONE.LOCAL
+SMB_PORT=28633
+KRB5_PORT=28634
+
+. $(dirname "$0")/docker.bash
+
+start() {
+    docker build -t ${IMAGE} - <<EOF
```
Comment (ncw) [inline fstest/testserver/init.d/TestSMBKerberos:16]: Neat approach to making a lightly customised docker :-)

Do you think we should be removing the image in stop()? Or is docker clever enough to realise it has the same hash so we won't get one extra image per run?

**Review by ncw — COMMENTED** [review]
This looks fantastic - thank you.

Great use of the integration test framework to test it too.

I have a question about the docker usage inline - I want to make sure we don't fill the integration server up with docker images!

File: fstest/testserver/init.d/TestSMBKerberos (hunk 1 above)
Comment (jgiannuzzi) [reply fstest/testserver/init.d/TestSMBKerberos:16]: Yes, this will benefit from caching, unless the user either deletes the image, or cleans the build cache.

Comment (jgiannuzzi) [reply fstest/testserver/init.d/TestSMBKerberos:16]: In other words, only the first run on a given docker host will actually need to do anything and the next invocations will be "free". Also we use an alpine image which means what needs to be downloaded and the resulting image are really small.

**Comment by jgiannuzzi** [comment]
By the way I went with the inline Dockerfile to avoid having to maintain an extra docker image like we do for HDFS, but I'm happy to change the approach if you'd like.

**Review by ncw — APPROVED** [review]
> By the way I went with the inline Dockerfile to avoid having to maintain an extra docker image like we do for HDFS, but I'm happy to change the approach if you'd like.

I think it is an excellent approach if the changes are small like here - I just wanted to check it was working how I thought it should!

This looks great - I will merge now - thank you.

**Comment by ncw** [comment]
@jgiannuzzi 

I'm having trouble getting the smb kerberos integration tests to run clean

https://pub.rclone.org/integration-tests/2025-07-02-010014/index.html

The tests are all failing like this - I think it is something to do with the local password storage that the docker image uses.

https://pub.rclone.org/integration-tests/2025-07-02-010014/smb-backend.smb-TestSMBKerberosrclone-5.txt

```
#7 exporting to image
#7 exporting layers done
#7 writing image sha256:122f9177f954bf807228d7924931e0a679033979fe2bb848e1cc99f4b4272309 done
#7 naming to docker.io/rclone/test-smb-kerberos done
#7 DONE 0.0s
f3f6a65a4ae4ddc93634b0385c0e8715d16faa68747c476d10b4c1ae85e2648c
ERROR(runtime): uncaught exception - kinit for rclone@RCLONE.LOCAL failed (Password has expired)

  File "/usr/lib/python3.12/site-packages/samba/netcmd/__init__.py", line 285, in _run
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/samba/netcmd/user/readpasswords/get_kerberos_ticket.py", line 146, in run
    creds.get_named_ccache(lp_ctx, output_krb5_ccache)
: exit status 255
```

You can test this locally with

```
cd rclone source
go install ./...
test_all -remotes TestSMBKerberos:rclone
```

**Comment by jgiannuzzi** [comment]
@ncw I'm currently away from a computer but I think this has to do with how I create the user in the docker image. It's now been long enough in the build cache that the password expired. A workaround would be to rebuild the image without cache so the user creation would run again, or even to prune the entire docker build cache. The solution would be to create the user with a password that doesn't expire, but I'd need to look at the docs to know which flag to use (if any).

**Comment by ncw** [comment]
Thanks for the hint @jgiannuzzi - I think I've fixed that in a97425d9cbee1da6507f404403fe441236e2e024

This is leaving only one failing test - any ideas on this? If I had to guess I'd say it is something to do with this https://github.com/rclone/rclone/blob/a97425d9cbee1da6507f404403fe441236e2e024/backend/smb/smb.go#L496 not working properly 

```
"./operations.test -test.v -test.timeout 1h0m0s -remote TestSMBKerberos:rclone -test.run '^TestMultithreadCopy$/^upload=false,size=134217727,streams=2$'" - Starting (try 5/5)
=== RUN   TestMultithreadCopy
    run.go:180: Remote "smb://ncw@localhost:28633/rclone/rclone-test-porepog9hecu", Local "Local file system at /tmp/rclone266871632", Modify Window "1ms"
=== RUN   TestMultithreadCopy/upload=false,size=134217727,streams=2
=== NAME  TestMultithreadCopy
    run.go:285: Failed to put "test-multithread-copy-false-134217727-2" to "smb://ncw@localhost:28633/rclone/rclone-test-porepog9hecu": Update ReadFrom failed: write rclone-test-porepog9hecu\test-multithread-copy-false-134217727-2: invalid response error: signing required
=== NAME  TestMultithreadCopy/upload=false,size=134217727,streams=2
    testing.go:1577: test executed panic(nil) or runtime.Goexit: subtest may have called FailNow on a parent test
--- FAIL: TestMultithreadCopy (0.82s)
    --- FAIL: TestMultithreadCopy/upload=false,size=134217727,streams=2 (0.82s)
FAIL
"./operations.test -test.v -test.timeout 1h0m0s -remote TestSMBKerberos:rclone -test.run '^TestMultithreadCopy$/^upload=false,size=134217727,streams=2$'" - Finished ERROR in 923.819906ms (try 5/5): exit status 1: Failed [TestMultithreadCopy/upload=false,size=134217727,streams=2]
```
