### PR TITLE
opendrive: resolve lag and truncate bugs fixes #5936

### LINKED ISSUE #5936: opendrive copy throws error despite 200 OK
#### The associated forum post URL from `https://forum.rclone.org`
N/A

#### What is the problem you are having with rclone?
Unable to copy files to opendrive (paid personal) using a basic config which wraps opendrive via crypt and chunker

```
[opendrivebase]
type = opendrive
username = <email>
password = <obfuscated_password>

[opendrivechunked]
type = chunker
remote = opendrivecrypt:
chunk_size = 500Mi

[opendrivecrypt]
type = crypt
remote = opendrivebase:data
password = <obfuscated_password>
password2 = <obfuscated_salt>
```

#### What is your rclone version (output from `rclone version`)
rclone v1.57.0

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Mac - darwin 12.0.1 (64 bit)

#### Which cloud storage system are you using? (e.g. Google Drive)
opendrive

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
rclone copy ./subdir opendrivechunked:myfolder/subdir -vv --timeout 15m --log-file /Users/myuser/mylog.log --dump-headers --transfers 1

I have attempted to fiddle with a few other flags to no avail

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

No obvious errors here, I can see the requests working fine in the verbose logs and the headers. abbreviated version is:

```
POST /api/v1/session/login.json
GET /api/v1/folder/list.json/<session_id>/0
<a few random GETs over root folders>
GET /api/v1/folder/itembyname.json/<session_id>/<account_id>?name=<unique_id_d> # a metadata file? id appears only once in logs
GET /api/v1/folder/itembyname.json/<session_id>/<account_id>?name=<unique_id_e> # file?
GET /api/v1/folder/itembyname.json/<session_id>/<account_id>?name=<unique_id_e> # file?
POST /api/v1/upload/create_file.json
POST /api/v1/upload/open_file_upload.json
POST /api/v1/upload/upload_file_chunk.json
... bunch more chunks uploaded ...
POST /api/v1/upload/upload_file_chunk.json
POST /api/v1/upload/close_file_upload.json
PUT /api/v1/file/filesettings.json
POST /api/v1/file/access.json
GET /api/v1/folder/itembyname.json/<session_id>/<account_id>?name=<unique_id_e> # file?
```
All requests return 200. Even the final `GET /api/v1/folder/itembyname.json/<session_id>/<account_id>?name=<unique_id_e>` returns `HTTP/1.1 200 OK` but rsync still throws the following error: 

```
ERROR : myfile.dat: Failed to copy: object not found
```

Is there maybe a gap between when the close_file_upload succeeds and the itembyname will correctly register? The 200 leads me to believe that it found the new object though...

After the failure rclone continues to move on to the next file, repeating uploading until all 3 retries are completed at which point  

I've attempted this with files smaller than my chunk (set to 500Mi), and with files bigger. Same results. close_file_upload -> filesettings -> access -> itembyname all return a 200, but then ERROR

```
2022/01/21 22:15:02 ERROR : myfile.dat: Failed to copy: object not found
2022/01/21 22:15:02 ERROR : Attempt 1/3 failed with 2 errors and: object not found
```

full logs at https://pastebin.com/HQZv6gpg

I will (rarely) get a pacer error, with the next attempt succeeding fine so I don't think it's a rate-limiting problem

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

### PR DESCRIPTION
**Pull request by scott-grimes**
#### What is the purpose of this change?
Resolves two issues with opendrive:
1) fetches metadata directly from `/file/info.json` in readMetaData when possible (if the object id is already known)

Previously all calls in readMetaData relied on the `/folder/itembyname.json` api which is buggy: items written to a directory take an arbitrary amount of time to appear via this endpoint, and the file info returned does not include the file hash.

2) resolves a bug caused by an undocumented feature of the `move_copy` endpoint which silently truncates new filenames to 255 char. rclone (correctly) throws an error when attempting to create a file or directory that surpasses the max length for opendrive, but there is no check performed in the move_copy command. Without such a check files written to the remote may have their names modified unknowingly. 

#### Was the change discussed in an issue or in the forum before?

https://github.com/rclone/rclone/issues/5936

#### Checklist

- [X] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [x] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [X] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

File: backend/opendrive/opendrive.go [hunk 1]
```diff
@@ -1027,6 +1033,32 @@ func (o *Object) readMetaData(ctx context.Context) (err error) {
...
+					o.id, o.fs.session.SessionID),
+			}
+			resp, err = o.fs.srv.CallJSON(ctx, &opts, nil, &fileInfo)
+			return o.fs.shouldRetry(ctx, resp, err)
+		})
+		if err != nil {
+			return fmt.Errorf("failed to get fileinfo: %w", err)
+		}
+
+		o.id = fileInfo.FileID
```
Comment (ncw) [inline backend/opendrive/opendrive.go:1055]: This feels like this should be an `if / else` with the setting of the `o.id` etc variables done after the `if / else` otherwise there is a bit of duplicated code here.

**Review by ncw — COMMENTED** [review]
This looks really good - thank you.

Looking things up by ID is always better.

I put some very minor comments about the code inline.

File: backend/opendrive/opendrive.go (hunk 1 above)
Comment (scott-grimes) [reply backend/opendrive/opendrive.go:1055]: done!

**Review by ncw — APPROVED** [review]
LGTM - thanks for fixing it up @buengese - I'll merge it now.
