### PR TITLE
fix error counter - fixes #3650

### LINKED ISSUE #3650: RClone Counts Errors twice for Copy operations
#### What is the problem you are having with rclone?
RClone counts errors twice for the copy operations

#### What is your rclone version (output from `rclone version`)
RClone 1.49.3

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu 18.04 LTS, 64 bit

####  Which cloud storage system are you using? (eg Google Drive)
Developing a new backend for RClone

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
copy

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

image

This happens because `fs.CountError(err)` is called once from within the `Copy()` function in `operations.go` and is then again called as part of `tr.Done(err)`. This results in the errors being counted twice. 

It looks like `fs.CountError` is again being called once at the end of all files, though I couldn't trace from where it is called. For every error, the count is 2n+1.

### PR DESCRIPTION
**Pull request by ankur0493**
#### What is the purpose of this change?
For few commands, RClone counts a error multiple times. This was fixed by
creating a new error type which keeps a flag to remember if the error has
already been counted or not.

#### Was the change discussed in an issue or in the forum before?
#3650 

#### Checklist

- [ x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [ ] I have added tests for all changes in this PR if appropriate.
- [ x] I have added documentation for the changes if appropriate.
- [x ] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [ ] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by ankur0493** [comment]
@ncw This change currently just covers the `Copy` function. We can extend the same change to a lot of other places to ensure errors aren't counted multiple times. I'll proceed if the approach looks good.

File: fs/fserrors/error.go [hunk 1]
```diff
@@ -230,6 +230,61 @@ func IsRetryAfterError(err error) bool {
...
+
+// Counted sets the isCounted variable on the error if it conforms to the
+// CountableError interface
+func Count(err error) {
+	if r, ok := err.(CountableError); ok {
+		r.Count()
+	}
+}
+
+
```
Comment (golangcibot) [inline fs/fserrors/error.go]: File is not `goimports`-ed (from `goimports`)
```suggestion

```

File: fs/fserrors/error.go [hunk 2]
```diff
@@ -230,6 +230,61 @@ func IsRetryAfterError(err error) bool {
...
+// IsCounted returns true if err conforms to the CountableError interface
+// and has already been counted
+func IsCounted(err error) bool {
+	if r, ok := err.(CountableError); ok {
+		return r.IsCounted()
+	}
+	return false
+}
+
+// Counted sets the isCounted variable on the error if it conforms to the
```
Comment (golangcibot) [inline fs/fserrors/error.go]: comment on exported function `Count` should be of the form `Count ...` (from `golint`)

**Comment by ncw** [comment]
Deduplication of the error is a very interesting approach that I hadn't though of.

I guess the question is: do the deduplication in the error itself; or do it in the `CountError` function?

I think doing it in the `CountError` function might be easier.

Let's say we kept a slice of the last 5 errors, we could ignore the error if it was one of the last 5 errors. (note that potentially we might need to unwrap the incoming error to match it).

Note that interface comparison is a little tricksy in go: https://play.golang.org/p/mzX8vbyeAar

I think just comparing with `==` will be OK as there are very few non pointer type errors (but there are a few).

**Comment by ankur0493** [comment]
> Let's say we kept a slice of the last 5 errors, we could ignore the error if it was one of the last 5 errors. 
Keeping a record of last x errors will never be 100% reliable. Let's say I am running 20 transfer threads with very small files, and all my transfers are failing. There will probably still be a possibility that we end up counting an error twice. However if we do that deduplication in the error itself, we can be sure that we won't count an error again.

> https://play.golang.org/p/mzX8vbyeAar
In this example, we are essentially doing `string("hello") == string("hello")`, which will return true. Will we see same behavior with the error interface?
We are already using different error interfaces and they work quite well.

**Comment by ncw** [comment]
> > Let's say we kept a slice of the last 5 errors, we could ignore the error if it was one of the last 5 errors.
> 
> Keeping a record of last x errors will never be 100% reliable. Let's say I am running 20 transfer threads with very small files, and all my transfers are failing. There will probably still be a possibility that we end up counting an error twice.

Hmm, possibly... However counting an error twice isn't catastrophic.  We could always size the internal buffer to `fs.Config.Transfers + fs.Config.Checkers`.

> However if we do that deduplication in the error itself, we can be sure that we won't count an error again.

Sure, but then we need to change every error site which it would be nice not to!

Thinking aloud:

It might be a better interface to do

```
err = fs.CountError(err)
```

Where CountError counts the error and returns a `Counted` wrapper for `err` if `err` isn't `Counted`.

This will mean that `errcheck` will find all the places we didn't update.

> > https://play.golang.org/p/mzX8vbyeAar
> 
> In this example, we are essentially doing `string("hello") == string("hello")`, which will return true. Will we see same behavior with the error interface?

Probably not. But we could do... For example https://golang.org/pkg/syscall/#EAGAIN

This would mean we count fewer errors that we should.

As long as we never count 0 errors when we had some errors this doesn't matter too much.

File: fs/operations/operations.go [hunk 3]
```diff
@@ -685,7 +685,7 @@ func checkIdentical(ctx context.Context, dst, src fs.Object) (differ bool, noHas
 	if !same {
 		err = errors.Errorf("%v differ", ht)
 		fs.Errorf(src, "%v", err)
-		fs.CountError(err)
+		err = fs.CountError(err)
```
Comment (golangcibot) [inline fs/operations/operations.go]: ineffectual assignment to `err` (from `ineffassign`)

File: fs/operations/operations.go [hunk 4]
```diff
@@ -716,7 +716,7 @@ func (c *checkMarch) DstOnly(dst fs.DirEntry) (recurse bool) {
 		}
 		err := errors.Errorf("File not in %v", c.fsrc)
 		fs.Errorf(dst, "%v", err)
-		fs.CountError(err)
+		err = fs.CountError(err)
```
Comment (golangcibot) [inline fs/operations/operations.go]: ineffectual assignment to `err` (from `ineffassign`)

File: fs/operations/operations.go [hunk 5]
```diff
@@ -734,7 +734,7 @@ func (c *checkMarch) SrcOnly(src fs.DirEntry) (recurse bool) {
 	case fs.Object:
 		err := errors.Errorf("File not in %v", c.fdst)
 		fs.Errorf(src, "%v", err)
-		fs.CountError(err)
+		err = fs.CountError(err)
```
Comment (golangcibot) [inline fs/operations/operations.go]: ineffectual assignment to `err` (from `ineffassign`)

File: fs/operations/operations.go [hunk 6]
```diff
@@ -784,7 +783,7 @@ func (c *checkMarch) Match(ctx context.Context, dst, src fs.DirEntry) (recurse b
 		} else {
 			err := errors.Errorf("is file on %v but directory on %v", c.fsrc, c.fdst)
 			fs.Errorf(src, "%v", err)
-			fs.CountError(err)
+			err = fs.CountError(err)
```
Comment (golangcibot) [inline fs/operations/operations.go]: ineffectual assignment to `err` (from `ineffassign`)

File: fs/operations/operations.go [hunk 7]
```diff
@@ -796,7 +795,7 @@ func (c *checkMarch) Match(ctx context.Context, dst, src fs.DirEntry) (recurse b
 		}
 		err := errors.Errorf("is file on %v but directory on %v", c.fdst, c.fsrc)
 		fs.Errorf(dst, "%v", err)
-		fs.CountError(err)
+		err = fs.CountError(err)
```
Comment (golangcibot) [inline fs/operations/operations.go]: ineffectual assignment to `err` (from `ineffassign`)

File: cmd/cmd.go [hunk 8]
```diff
@@ -189,11 +189,11 @@ func NewFsSrcDstFiles(args []string) (fsrc fs.Fs, srcFileName string, fdst fs.Fs
 	fdst, err := cache.Get(dstRemote)
 	switch err {
 	case fs.ErrorIsFile:
-		fs.CountError(err)
+		err = fs.CountError(err)
```
Comment (golangcibot) [inline cmd/cmd.go]: ineffectual assignment to `err` (from `ineffassign`)

**Comment by ankur0493** [comment]
@ncw 

> Thinking aloud:
>It might be a better interface to do
err = fs.CountError(err)
>Where CountError counts the error and returns a Counted wrapper for err if err isn't Counted.
> This will mean that errcheck will find all the places we didn't update.

This sounds like a good approach. I updated my pull request with changes wherever were needed. All the tests are also passing now.

**Comment by ncw** [comment]
That is looking good now - I'll merge it - thank you :-)
