### PR TITLE
s3: fix Content-MD5 for Object Lock uploads and add GCS quirk

### LINKED ISSUE #9199: s3: Object Lock integration test failures on AWS and GCS
Following the merge of #9173 (Object Lock support), the integration tests at https://integration.rclone.org revealed failures on both AWS S3 and GCS.

## 1. AWS: Content-MD5 required for Object Lock (fix ready)

AWS S3 requires a `Content-MD5` header for PutObject requests with Object Lock parameters. Since rclone passes a non-seekable `io.Reader` as the request body, the AWS SDK cannot compute the checksum automatically.

**Fix:** Buffer the body and compute MD5 manually for singlepart PutObject and presigned requests. Multipart is unaffected (Object Lock headers go on CreateMultipartUpload which has no body). I'll open a PR shortly.

**Affected tests:** TestS3 and TestS3,directory_markers — ObjectLock/Retention and ObjectLock/LegalHold

## 2. GCS: Non-standard Object Lock implementation (needs discussion)

GCS doesn't fully follow the S3 Object Lock standard:

- **BypassGovernanceRetention**: GCS ignores the standard `x-amz-bypass-governance-retention` header and requires its own `x-goog-bypass-governance-retention` instead ([GCS docs](https://docs.cloud.google.com/storage/docs/xml-api/put-object-retention)). This means test cleanup can't delete locked objects.
- **Legal Hold**: `PutObjectLegalHold` / `GetObjectLegalHold` APIs are not implemented in GCS's S3-compatible API.
- Retention itself (GOVERNANCE/COMPLIANCE modes) works fine.

This is tricky because it's not a simple "supported or not" — GCS partially supports Object Lock but deviates from the standard. Since we use GOVERNANCE mode with BypassGovernanceRetention for test cleanup, the non-standard bypass header means **we risk leaving behind undeletable objects on GCS**.

**Affected tests:** TestS3GCS — ObjectLock/Retention, ObjectLock/LegalHold, and ObjectLock/SetAfterUpload

### Options for handling GCS

**a) Skip ObjectLock tests on GCS via quirk** (`object_lock_supported: false` in the GCS provider config). Simple but hides the fact that retention actually works on GCS.

**b) Graceful degradation with skip-on-failure**: Treat Legal Hold and bypass-delete as optional capabilities — probe each before use and skip the subtest if unsupported, rather than failing. This keeps the tests green on providers with partial support, but may leave behind undeletable objects when bypass isn't available. Given that risk, one could argue these tests add little value if they can't clean up reliably and might as well be removed.

**c) Short retention with wait-based cleanup**: Same graceful degradation as (b), but instead of risking leftover objects, use a short retention period (e.g. 60s). If bypass-delete fails, wait for the retention to expire and then clean up normally. The downside is that clock skew between client and server becomes a real concern at these short durations — a few seconds of drift could cause the initial retention request to be rejected (date in the past from the server's perspective) or the cleanup to fail (retention not yet expired from the server's perspective).

My preference would be **(a)** — adding a quirk to skip the ObjectLock tests on GCS. Options (b) and (c) feel like rabbit holes where we'd end up working around GCS-specific S3 incompatibilities rather than focusing on the actual Object Lock feature. The quirk approach is clean, minimal, and users could override it via `object_lock_supported = true` if needed.

@ncw What do you think?

Chris

### PR DESCRIPTION
**Pull request by chris081519-crypto**
AWS S3 requires Content-MD5 for PutObject with Object Lock parameters. Since rclone passes a non-seekable io.Reader, the SDK cannot compute checksums automatically. Buffer the body and compute MD5 manually for singlepart PutObject and presigned request uploads when Object Lock parameters are set. Multipart uploads are unaffected as Object Lock headers go on CreateMultipartUpload which has no body.

Add object_lock_supported provider quirk (default true) to allow skipping Object Lock integration tests on providers with incomplete S3 API support. Set to false for GCS which uses non-standard x-goog-bypass-governance-retention header and doesn't implement PutObjectLegalHold/GetObjectLegalHold.

Add Multipart and Presigned subtests to Object Lock integration tests to cover all three upload paths.

#### What is the purpose of this change?
Adding Content-MD5 Headers when using Object Lock on AWS for PutObject.
Adding provider quirk to skip GCP testing with Object Lock (as their implementation deviates from the standard).

#### Was the change discussed in an issue or in the forum before?

Fixes #9199

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [x] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

File: backend/s3/s3.go [hunk 1]
```diff
@@ -4635,6 +4665,19 @@ func (o *Object) uploadSinglepartPutObject(ctx context.Context, req *s3.PutObjec
...
+		if err != nil {
+			return etag, lastModified, nil, fmt.Errorf("failed to read body for Content-MD5: %w", err)
+		}
+		md5sum := md5.Sum(buf)
+		md5base64 := base64.StdEncoding.EncodeToString(md5sum[:])
+		req.ContentMD5 = &md5base64
+		in = bytes.NewReader(buf)
+	}
 	// Create the presigned request
 	putReq, err := s3.NewPresignClient(o.fs.c).PresignPutObject(ctx, req, s3.WithPresignExpires(15*time.Minute))
```
Comment (ncw) [inline backend/s3/s3.go:4687]: The MD5 buffering logic (ReadAll + md5.Sum + base64 encode + set ContentMD5) is duplicated verbatim between this function and `uploadSinglepartPutObject` above. Consider extracting a helper, e.g.:

```go
func bufferForObjectLockMD5(req *s3.PutObjectInput, in io.Reader) (io.Reader, error) {
	if req.ObjectLockMode == "" && req.ObjectLockRetainUntilDate == nil && req.ObjectLockLegalHoldStatus == "" {
		return in, nil
	}
	buf, err := io.ReadAll(in)
	if err != nil {
		return nil, fmt.Errorf("failed to read body for Content-MD5: %%w", err)
	}
	md5sum := md5.Sum(buf)
	md5base64 := base64.StdEncoding.EncodeToString(md5sum[:])
	req.ContentMD5 = &md5base64
	return bytes.NewReader(buf), nil
}
```

Then both call sites become a one-liner.

Comment (chris081519-crypto) [reply backend/s3/s3.go:4687]: Sure, makes sense.
I adjusted that.

File: backend/s3/s3.go [hunk 2]
```diff
@@ -4609,8 +4624,31 @@ func (o *Object) uploadMultipart(ctx context.Context, src fs.ObjectInfo, in io.R
 }
 
 // Upload a single part using PutObject
```
Comment (ncw) [inline backend/s3/s3.go]: This comment is now in the wrong place - it belongs to `uploadSinglepartPutObject` below

**Review by ncw — CHANGES_REQUESTED** [review]
That looks great - thanks.

One incredibly minor thing inline!

Fix that and I will merge - thank you :-)

File: backend/s3/s3.go (hunk 2 above)
Comment (chris081519-crypto) [reply backend/s3/s3.go]: Ouch, shame on me... I'm really sorry.
Thanks for spotting.

**Comment by chris081519-crypto** [comment]
Just a comment about the Pipeline Checks...
I noticed that the windows as well as the go1.25 parts seem to be non-deterministic. They fail from time to time and one has to re-trigger it by an empty commit to reach a "clean" status.
