### PR TITLE
putio: add status code 206 - fixes #6079

### LINKED ISSUE #6079: [putio] unexpected status code (206)
#### What is the problem you are having with rclone?
putio backend don't recognize status 206 for multi-thread copy

#### What is your rclone version (output from `rclone version`)
```
rclone v1.59.0-beta.6050.54c9c3156
- os/version: Microsoft Windows 11 Pro 21H2 (64 bit)
- os/kernel: 10.0.22000.556 (x86_64)
- os/type: windows
- os/arch: amd64
- go/version: go1.17.8
- go/linking: dynamic
- go/tags: cmount
```

#### Which cloud storage system are you using? (e.g. Google Drive)
putio

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
`.\rclone.exe copy putio:test/a.mp4 . -P -vv`

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
```
2022/04/01 22:27:53 DEBUG : rclone: Version "v1.59.0-beta.6050.54c9c3156" starting with parameters ["E:\\Downloads\\rclone.exe" "copy" "putio:test/a.mp4" "." "-P" "-vv"]
2022/04/01 22:27:53 DEBUG : Creating backend with remote "putio:test/a.mp4"
2022/04/01 22:27:53 DEBUG : Using config file from "C:\\Users\\rafma0\\.config\\rclone\\rclone.conf"
2022/04/01 22:27:54 DEBUG : fs cache: adding new entry for parent of "putio:test/a.mp4", "putio:test"
2022/04/01 22:27:54 DEBUG : Creating backend with remote "."
2022/04/01 22:27:54 DEBUG : fs cache: renaming cache item "." to be canonical "//?/E:/Downloads"
2022-04-01 22:27:54 DEBUG : a.mp4: Need to transfer - File not found at Destination
2022-04-01 22:27:54 INFO  : Writing sparse files: use --local-no-sparse or --multi-thread-streams 0 to disable
2022-04-01 22:27:54 DEBUG : a.mp4: Starting multi-thread copy with 4 parts of size 474.875Mi
2022-04-01 22:27:54 DEBUG : a.mp4: multi-thread copy: stream 2/4 (497942528-995885056) size 474.875Mi starting
2022-04-01 22:27:54 DEBUG : a.mp4: multi-thread copy: stream 4/4 (1493827584-1991764913) size 474.870Mi starting
2022-04-01 22:27:54 DEBUG : a.mp4: multi-thread copy: stream 3/4 (995885056-1493827584) size 474.875Mi starting
2022-04-01 22:27:54 DEBUG : a.mp4: multi-thread copy: stream 1/4 (0-497942528) size 474.875Mi starting
2022-04-01 22:27:56 DEBUG : a.mp4: multi-thread copy: stream 3/4 failed: multipart copy: failed to open source: unexpected status code (206) response while doing GET to https://nyc1.put.io/download/...
2022-04-01 22:27:56 DEBUG : a.mp4: multi-thread copy: stream 4/4 failed: multipart copy: failed to open source: Get "https://nyc1.put.io/download/...
2022-04-01 22:27:56 DEBUG : a.mp4: multi-thread copy: stream 1/4 failed: multipart copy: failed to open source: Get "https://nyc1.put.io/download/...
2022-04-01 22:27:56 DEBUG : a.mp4: multi-thread copy: stream 2/4 failed: multipart copy: failed to open source: Get "https://nyc1.put.io/download/...
```

Changing this https://github.com/rclone/rclone/blob/4f78226f8b96257216ce6578ad249e20c195bd53/backend/putio/object.go#L247 from 200 to 206 seems to fix the problem (but breaks for non multi-thread 🤣)

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

### PR DESCRIPTION
**Pull request by rafma0**
#### What is the purpose of this change?
adds support to multi-thread-streams on putio backend

#### Was the change discussed in an issue or in the forum before?
#6079

#### Checklist

- [X] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [X] I have added tests for all changes in this PR if appropriate.
- [X] I have added documentation for the changes if appropriate.
- [X] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [X] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

File: backend/putio/error.go [hunk 1]
```diff
@@ -12,11 +12,13 @@ import (
 	"github.com/rclone/rclone/lib/pacer"
 )
 
-func checkStatusCode(resp *http.Response, expected int) error {
-	if resp.StatusCode != expected {
-		return &statusCodeError{response: resp}
+func checkStatusCode(resp *http.Response, expected []int) error {
+	for _, code := range expected {
```
Comment (ncw) [inline backend/putio/error.go:16]: I suggest you make this

    func checkStatusCode(resp *http.Response, expected ...int) error {

Which is a bit of syntax which means allow any number of int parameters this makes `expected` into a `[]int` so nothing else in this function needs to change

File: backend/putio/fs.go [hunk 2]
```diff
@@ -302,7 +302,7 @@ func (f *Fs) createUpload(ctx context.Context, name string, size int64, parentID
 		if err != nil {
 			return false, err
 		}
-		if err := checkStatusCode(resp, 201); err != nil {
+		if err := checkStatusCode(resp, []int{201}); err != nil {
```
Comment (ncw) [inline backend/putio/fs.go:305]: ...This can then become (ie it doesn't need to change)

    checkStatusCode(resp, 201);

File: backend/putio/object.go [hunk 3]
```diff
@@ -244,7 +244,7 @@ func (o *Object) Open(ctx context.Context, options ...fs.OpenOption) (in io.Read
 		if err != nil {
 			return shouldRetry(ctx, err)
 		}
-		if err := checkStatusCode(resp, 200); err != nil {
+		if err := checkStatusCode(resp, []int{200, 206}); err != nil {
```
Comment (ncw) [inline backend/putio/object.go:247]: And this can become `checkStatusCode(resp, 200, 206)`

**Review by ncw — COMMENTED** [review]
This is a great fix - thank you.

Its been failing in the daily integration tests here: https://pub.rclone.org/integration-tests/current/ in the TestMultithreadCopy tests for putio - I just hadn't had time to fix!

I put a suggestion on how to make the code a bit neater inline. Can you fix it up like that then force push - thank you :-)

Also if you could put the problem that is fixed in the first line of the commit message that will help users as the changelog is generated from that, so something like

```
putio: fix multithread download and other ranged requests

Before this change the 206 responses from putio Range requests were being
returned as errors.

This change checks for 200 and 206 in the GET response now.
```

This fix should probably go into a point release.

**Comment by rafma0** [comment]
Hi, just did the changes requested and force pushed, hope its correct :)

**Review by ncw — APPROVED** [review]
That looks great - thank you.

I'll merge this for 1.59 and 1.58.1 :-)
