### PR TITLE
Correct exitcode on Transfer Limit Exceeded flag. Fixes #3203

### LINKED ISSUE #3203: Incorrect Exit Code for Transfer Limit Exceeded
#### What is the problem you are having with rclone?

Incorrect Exit Code by rclone when the specified max-transfer limit is reached. As per the docs @ https://rclone.org/docs/#exit-code, the exit-code should be `8` instead of `7` which indicates a fatal error.

This is just my guess from a brief overview of the related code, but I believe that the error stems from https://github.com/ncw/rclone/blob/7d70e9266446901e93a888212edd06765821047b/fs/sync/sync.go#L178-L183 where the actual error is added to which fails the eventual comparison test for the error type.

#### What is your rclone version (output from `rclone version`)

```
rclone v1.47.0-062-g99bc013c-beta
- os/arch: linux/amd64
- go version: go1.12.5
```

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

`Debian 9 64-bit`

####  Which cloud storage system are you using? (eg Google Drive)

`Google Drive`

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

`rclone sync Drive: DriveCopy: --tpslimit=5 --tpslimit-burst=50 --max-transfer=700G`

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

Relevant Lines:

```
2019/05/16 07:54:40 ERROR : Cancelling sync due to fatal error: Max transfer limit reached as set by --max-transfer
2019/05/16 07:54:40 INFO  : Google drive root '': Waiting for checks to finish
2019/05/16 07:54:40 INFO  : Google drive root '': Waiting for transfers to finish
2019/05/16 07:54:41 INFO  : o6i2cgd36bmi2nva56ubo4a268/i28c365mh5iu29bbbq5h5bf960/q58f203e7ps6gblq0fu0f36954/o6omqo0u6b7sb4rjhdjf7qsmtg/dajheiohfhb8b7vag018ke
paucfq3fau0kb3l75fqstcii04ch32jcj7p79rnv86jd6v4v8atj3p81pcq460pge65ut8p7n02ptt7eo: Copied (server side copy)
2019/05/16 07:54:41 ERROR : Fatal error received - not attempting retries
2019/05/16 07:54:41 Failed to sync: Max transfer limit reached as set by --max-transfer
```

### PR DESCRIPTION
**Pull request by anuar45**
#### What is the purpose of this change?

Send correct exit code(8) when transfer is limited by --max-transfer flag.

#### Was the change discussed in an issue or in the forum before?

Issue #3203

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [x] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

File: cmd/cmd.go [hunk 1]
```diff
@@ -442,7 +443,7 @@ func resolveExitCode(err error) {
 		os.Exit(exitCodeFileNotFound)
 	case unwrapped == errorUncategorized:
 		os.Exit(exitCodeUncategorizedError)
-	case unwrapped == accounting.ErrorMaxTransferLimitReached:
+	case stderrors.Is(err, accounting.ErrorMaxTransferLimitReached):
```
Comment (ncw) [inline cmd/cmd.go]: We can't use `errors.Is` yet as we still need to support go1.11

However you shouldn't need it as we use `fserrors.Cause` which does a pretty similar thing.

File: fs/fserrors/error.go [hunk 2]
```diff
@@ -116,6 +116,10 @@ func (err wrappedFatalError) Cause() error {
 	return err.error
 }
 
+func (err wrappedFatalError) Unwrap() error {
```
Comment (ncw) [inline fs/fserrors/error.go]: If we aren't using `errors.Is` we don't need the `Unwrap` as we have `Cause` which is what pkg/errors uses.

**Comment by ncw** [comment]
That looks great now - thank you :-)

I'll merge it.
